"use client";

import { useState } from "react";
import { LiquidButton } from "@/components/ui/liquid-glass-button";
import MarkdownRenderer from "@/components/MarkdownRenderer";

interface DocumentPreviewProps {
  fullText: string;
  onExport: (format: "pdf" | "docx") => void;
  isExporting: boolean;
}

export default function DocumentPreview({ fullText, onExport, isExporting }: DocumentPreviewProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(fullText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      console.warn("Clipboard API unavailable");
    }
  };

  return (
    <div className="flex flex-col h-full animate-fade-in space-y-8 relative z-10 w-full max-w-4xl mx-auto">

      {/* Toolbar */}
      <div className="flex justify-between items-center bg-card p-4 rounded-xl sticky top-20 z-20 border border-border shadow-md">
        <div className="flex gap-4">
          <LiquidButton
            onClick={() => onExport("pdf")}
            disabled={isExporting}
            className="text-foreground border-border hover:bg-accent px-6 py-2 text-sm"
            size={'lg'}
            variant="ghost"
          >
            {isExporting ? "Exporting..." : "Download PDF"}
          </LiquidButton>
          <LiquidButton
            onClick={() => onExport("docx")}
            disabled={isExporting}
            className="text-foreground border-border hover:bg-accent px-6 py-2 text-sm"
            size={'lg'}
            variant="ghost"
          >
            Download DOCX
          </LiquidButton>
        </div>

        <button
          onClick={handleCopy}
          className="text-muted-foreground hover:text-foreground transition-colors text-sm font-medium flex items-center gap-2 px-4 py-2 hover:bg-accent rounded-lg"
        >
          {copied ? "Copied!" : "Copy Text"}
        </button>
      </div>

      {/* A4 Paper Simulation */}
      <div className="bg-white text-foreground shadow-lg border border-border mx-auto w-full min-h-[800px] p-12 md:p-16 rounded-sm relative overflow-hidden">
        {/* Standard Legal Header Pattern */}
        <div className="absolute top-0 left-0 w-full h-0.5 bg-border" />

        <div className="prose prose-neutral max-w-none font-serif leading-loose">
          <MarkdownRenderer content={fullText} />
        </div>

        {/* Footer Watermark */}
        <div className="absolute bottom-4 right-8 text-[10px] text-muted-foreground font-mono select-none">
          Generated by ClauseWala.
        </div>
      </div>

      {/* Spacer for scroll */}
      <div className="h-20" />
    </div>
  );
}
