import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service — ClauseWala.",
    description: "Terms and conditions for using ClauseWala's AI-powered legal document generation platform.",
};

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background text-foreground">
            <Navbar />

            <main className="max-w-3xl mx-auto px-6 sm:px-8 pt-28 md:pt-36 pb-24">
                <div className="animate-fade-in">
                    <p className="text-[11px] font-mono uppercase tracking-[0.2em] text-muted-foreground/60 mb-4">Legal</p>
                    <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-2">Terms of Service</h1>
                    <p className="text-[13px] text-muted-foreground mb-12">Last updated: February 21, 2026</p>

                    <div className="space-y-10">
                        <Section title="1. Acceptance of Terms">
                            <p>
                                By accessing or using ClauseWala (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
                                If you do not agree to these terms, do not use the Service. The Service is operated from India and
                                is governed by the laws of India.
                            </p>
                        </Section>

                        <Section title="2. Description of Service">
                            <p>
                                ClauseWala is an AI-powered web application that helps users generate legal document drafts including
                                NDAs, MOUs, appointment letters, and other business documents tailored for Indian jurisdiction.
                                The Service uses artificial intelligence to create document blueprints and full-text drafts based
                                on user inputs.
                            </p>
                        </Section>

                        <Section title="3. Important Disclaimer — Not Legal Advice">
                            <div className="bg-destructive/5 border border-destructive/20 rounded-lg p-4 text-[13px]">
                                <p className="font-semibold text-destructive mb-2">⚠️ Critical Notice</p>
                                <p>
                                    ClauseWala generates <strong>draft documents</strong> using AI. These drafts are <strong>not
                                    legal advice</strong> and do not constitute a lawyer-client relationship. All generated documents
                                    should be reviewed by a qualified legal professional before signing or execution. ClauseWala
                                    makes no warranties regarding the legal validity, enforceability, or completeness of any
                                    generated document.
                                </p>
                            </div>
                        </Section>

                        <Section title="4. User Responsibilities">
                            <ul>
                                <li>You must provide accurate information in document forms</li>
                                <li>You are responsible for reviewing all generated documents before use</li>
                                <li>You must not use the Service to generate fraudulent, illegal, or harmful documents</li>
                                <li>You must not attempt to reverse-engineer, scrape, or overload the Service</li>
                                <li>You are solely responsible for how you use any documents generated by the Service</li>
                            </ul>
                        </Section>

                        <Section title="5. Intellectual Property">
                            <p>
                                <strong>Your documents:</strong> You retain full ownership of the content you input and the documents
                                generated for you through the Service. ClauseWala does not claim any ownership over your generated documents.
                            </p>
                            <p>
                                <strong>Our platform:</strong> The ClauseWala name, logo, UI design, clause templates, prompt engineering,
                                and underlying technology are our intellectual property and may not be copied, modified, or distributed
                                without written permission.
                            </p>
                        </Section>

                        <Section title="6. AI-Generated Content">
                            <p>
                                Documents are generated using third-party AI models. While we strive for accuracy:
                            </p>
                            <ul>
                                <li>AI outputs may contain errors, omissions, or outdated legal references</li>
                                <li>Generated clauses may not cover all scenarios relevant to your situation</li>
                                <li>Risk assessments are indicative and not a substitute for professional legal review</li>
                                <li>We continuously improve our templates but cannot guarantee perfection</li>
                            </ul>
                        </Section>

                        <Section title="7. Limitation of Liability">
                            <p>
                                To the maximum extent permitted by Indian law, ClauseWala shall not be liable for any indirect,
                                incidental, special, consequential, or punitive damages arising from your use of the Service,
                                including but not limited to losses from reliance on generated documents. Our total liability
                                shall not exceed the amount paid by you for the Service in the 12 months preceding the claim.
                            </p>
                        </Section>

                        <Section title="8. Service Availability">
                            <p>
                                We aim to keep ClauseWala available 24/7 but do not guarantee uninterrupted access. The Service
                                may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control.
                                We reserve the right to modify, suspend, or discontinue any part of the Service at any time.
                            </p>
                        </Section>

                        <Section title="9. Pricing & Payments">
                            <p>
                                ClauseWala is currently offered as a free service during the early access period. We reserve the
                                right to introduce paid plans in the future. Users will be notified of any pricing changes at
                                least 30 days in advance.
                            </p>
                        </Section>

                        <Section title="10. Termination">
                            <p>
                                We may suspend or terminate your access to the Service at our discretion if you violate these
                                terms or misuse the platform. You may stop using the Service at any time.
                            </p>
                        </Section>

                        <Section title="11. Governing Law & Disputes">
                            <p>
                                These terms are governed by the laws of India. Any disputes arising from the use of ClauseWala
                                shall be subject to the exclusive jurisdiction of the courts in India. We encourage users to
                                contact us first to resolve any issues amicably.
                            </p>
                        </Section>

                        <Section title="12. Changes to Terms">
                            <p>
                                We may update these Terms from time to time. Material changes will be communicated via the
                                Service. Continued use after changes constitutes acceptance of the revised terms.
                            </p>
                        </Section>

                        <Section title="13. Contact">
                            <p>For questions about these terms:</p>
                            <ul>
                                <li>Email: <strong>legal@clausewala.com</strong></li>
                            </ul>
                        </Section>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section>
            <h2 className="text-lg font-semibold tracking-tight text-foreground mb-3">{title}</h2>
            <div className="text-[14px] text-muted-foreground leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_strong]:text-foreground">
                {children}
            </div>
        </section>
    );
}
