import React from "react";
import { FormDefinition } from "@/lib/gfe/schema";

interface PdfGeneratorProps {
  formDef: FormDefinition;
  data: Record<string, any>;
}

export const PdfReplicaGenerator = React.forwardRef<HTMLDivElement, PdfGeneratorProps>(
  ({ formDef, data }, ref) => {
    // A simple handlebar-like replacement for our declarative templateText
    let populatedText = formDef.templateText;

    // Replace {{key}} with actual data or underline if empty
    formDef.fields.forEach((field) => {
      const val = data[field.key] || "__________________";
      const regex = new RegExp(`\\{\\{(?:\\s+)?${field.key}(?:\\s+)?\\}\\}`, "g");
      populatedText = populatedText.replace(regex, `\u00A0${val}\u00A0`);
    });

    // Split text by lines to respect formatting
    const paragraphs = populatedText.split("\\n");

    return (
      <div
        ref={ref}
        className="print-section bg-white text-black p-12 max-w-4xl mx-auto shadow-2xl border border-gray-100 min-h-[1056px] relative font-serif"
        style={{ width: "210mm", height: "auto", minHeight: "297mm", padding: "20mm", fontFamily: '"Times New Roman", Times, serif' }}
      >
        <div className="absolute top-4 right-6 text-[10px] text-gray-500 font-sans text-right print:block">
          <div>Digitally structured version of official Government Gazette form.</div>
          <div>Form ID: {formDef.id} | Ver {formDef.version} | Act: {formDef.act}</div>
          <div>Generated by ClauseWala Compliance Infrastructure</div>
        </div>

        <div className="text-center mb-10 pt-8">
          <h2 className="text-[1.1rem] font-bold underline mb-2 tracking-wide uppercase">
            {formDef.formNumber}
          </h2>
          <h1 className="text-[1.3rem] font-bold uppercase tracking-widest mb-2 leading-snug">
            {formDef.title}
          </h1>
          <h3 className="text-[1.1rem] text-gray-800">
            (See {formDef.sectionReference})
          </h3>
        </div>

        <div className="text-justify text-[1.15rem] leading-[2.2] space-y-6 whitespace-pre-wrap">
          {paragraphs.map((p, i) => (
            <p key={i} className={`${p.trim() === "" ? "hidden" : "block"}`}>
              {p}
            </p>
          ))}
        </div>

        {/* Placeholder for Signature/Seal mapping logic specifically for Form 1/similar */}
        <div className="mt-32 w-full">
          {/* The signature and seal are part of the template paragraph, but could also be mapped explicitly 
                if we had a coordinate mapping strategy. For now, it flows with text. */}
        </div>
      </div>
    );
  }
);

PdfReplicaGenerator.displayName = "PdfReplicaGenerator";
