import type { DocumentTemplate } from "@/types";

export const appointmentLetterTemplate: DocumentTemplate = {
    type: "appointment-letter",
    label: "Appointment Letter",
    description:
        "Issue a legally compliant appointment letter covering CTC, probation, notice period, and company policies.",
    isTwoParty: false,
    fields: [
        {
            name: "employeeName",
            label: "Employee's Full Name",
            type: "text",
            placeholder: "e.g. Vikram Mehta",
            required: true,
        },
        {
            name: "employeeAddress",
            label: "Employee's Address",
            type: "textarea",
            placeholder: "Full residential address",
            required: false,
        },
        {
            name: "designation",
            label: "Designation / Job Title",
            type: "text",
            placeholder: "e.g. Product Manager",
            required: true,
        },
        {
            name: "department",
            label: "Department",
            type: "text",
            placeholder: "e.g. Product",
            required: true,
        },
        {
            name: "dateOfJoining",
            label: "Date of Joining",
            type: "date",
            required: true,
        },
        {
            name: "ctcAnnual",
            label: "Annual CTC (₹)",
            type: "text",
            placeholder: "e.g. ₹24,00,000",
            required: true,
        },
        {
            name: "ctcBreakdown",
            label: "CTC Breakdown",
            type: "textarea",
            placeholder: "Basic: ₹10,00,000 | HRA: ₹4,00,000 | PF: ₹2,40,000 | Special: ₹5,60,000 | Gratuity: ₹2,00,000",
            required: true,
            description: "Detailed salary structure as per Indian payroll norms.",
        },
        {
            name: "probationPeriod",
            label: "Probation Period",
            type: "select",
            required: true,
            options: [
                { label: "3 Months", value: "3-months" },
                { label: "6 Months", value: "6-months" },
                { label: "No Probation", value: "none" },
            ],
        },
        {
            name: "noticePeriod",
            label: "Notice Period",
            type: "select",
            required: true,
            options: [
                { label: "1 Month", value: "1-month" },
                { label: "2 Months", value: "2-months" },
                { label: "3 Months", value: "3-months" },
            ],
        },
        {
            name: "workLocation",
            label: "Work Location",
            type: "text",
            placeholder: "e.g. Mumbai, Maharashtra",
            required: true,
        },
        {
            name: "workingHours",
            label: "Working Hours",
            type: "text",
            placeholder: "e.g. 9:30 AM – 6:30 PM, Monday to Friday",
            required: false,
        },
        {
            name: "leavePolicy",
            label: "Leave Entitlement (Annual)",
            type: "text",
            placeholder: "e.g. 24 Paid Leaves + 12 Public Holidays",
            required: false,
        },
        {
            name: "includeNDA",
            label: "Include Confidentiality / NDA Clause?",
            type: "checkbox",
            required: false,
            description: "Embed a non-disclosure obligation within the appointment letter.",
        },
        {
            name: "includeNonCompete",
            label: "Include Non-Compete Clause?",
            type: "checkbox",
            required: false,
            description: "Note: Post-employment non-compete is generally unenforceable in India (S.27, Indian Contract Act).",
        },
        {
            name: "includeIPAssignment",
            label: "Include IP Assignment Clause?",
            type: "checkbox",
            required: false,
            description: "All work product created during employment belongs to the company.",
        },
        {
            name: "includeCodeOfConduct",
            label: "Reference Code of Conduct?",
            type: "checkbox",
            required: false,
        },
        {
            name: "additionalTerms",
            label: "Additional Terms",
            type: "textarea",
            placeholder: "e.g. Relocation allowance, medical insurance details, performance bonus...",
            required: false,
        },
    ],
    defaultClauses: [
        "Appointment Header & Date",
        "Employee Identification",
        "Designation, Department & Reporting",
        "Date of Joining",
        "Compensation Structure (CTC Breakdown)",
        "Probation & Confirmation",
        "Working Hours & Location",
        "Leave Policy",
        "Notice Period & Termination",
        "Code of Conduct & Discipline",
        "Confidentiality & NDA",
        "IP Assignment",
        "Governing Law",
        "Acceptance & Signature Block",
    ],
};
