import type { DocumentTemplate } from "@/types";

export const boardResolutionTemplate: DocumentTemplate = {
    type: "board-resolution",
    label: "Board Resolution",
    description:
        "Draft a board resolution for funding rounds, ESOP pools, bank accounts, or corporate actions.",
    isTwoParty: false,
    fields: [
        {
            name: "resolutionPurpose",
            label: "Purpose of Resolution",
            type: "select",
            required: true,
            options: [
                { label: "Bank Account Opening / Change of Signatory", value: "bank-account" },
                { label: "ESOP Pool Creation / Grant Approval", value: "esop" },
                { label: "Share Allotment (Investment Round)", value: "share-allotment" },
                { label: "Appointment / Removal of Director", value: "director-change" },
                { label: "Registered Office Change", value: "office-change" },
                { label: "Borrowing / Loan Approval", value: "borrowing" },
            ],
        },
        {
            name: "meetingType",
            label: "Meeting Type",
            type: "select",
            required: true,
            options: [
                { label: "Board Meeting", value: "board" },
                { label: "Circular Resolution (without meeting)", value: "circular" },
                { label: "Extra-Ordinary General Meeting (EGM)", value: "egm" },
            ],
        },
        {
            name: "meetingDate",
            label: "Date of Meeting / Resolution",
            type: "date",
            required: true,
        },
        {
            name: "meetingTime",
            label: "Time of Meeting",
            type: "text",
            placeholder: "e.g. 11:00 AM IST",
            required: false,
        },
        {
            name: "meetingVenue",
            label: "Venue / Mode",
            type: "text",
            placeholder: "e.g. Registered Office / Video Conference",
            required: true,
        },
        {
            name: "directorsPresent",
            label: "Directors / Members Present",
            type: "textarea",
            placeholder: "e.g. 1. Rajesh Kumar (DIN: 12345678) — Chairperson\n2. Priya Sharma (DIN: 87654321)",
            required: true,
            description: "List all directors/members present with DIN numbers.",
        },
        {
            name: "quorumConfirmation",
            label: "Quorum Confirmed?",
            type: "checkbox",
            required: false,
            description: "Confirm that quorum requirements (minimum 2 directors or 1/3rd) are met.",
        },
        {
            name: "resolutionText",
            label: "Resolution Details",
            type: "textarea",
            placeholder: "Describe the specific resolution being passed — e.g. \"RESOLVED THAT the company hereby approves creation of an ESOP pool of 10% of fully diluted share capital...\"",
            required: true,
            description: "The core operative text of the resolution.",
        },
        {
            name: "authorizedPerson",
            label: "Person Authorized to Execute",
            type: "text",
            placeholder: "e.g. Rajesh Kumar, Director",
            required: true,
            description: "Who is authorized to sign documents / take actions pursuant to this resolution.",
        },
        {
            name: "additionalNotes",
            label: "Additional Notes / Conditions",
            type: "textarea",
            placeholder: "Any conditions, timelines, or filing requirements",
            required: false,
        },
        {
            name: "includeROCFiling",
            label: "Reference ROC Filing Requirement?",
            type: "checkbox",
            required: false,
            description: "Applicable for director changes, share allotments, office changes, etc.",
        },
    ],
    defaultClauses: [
        "Resolution Header & Company Details",
        "Meeting Details (Date, Time, Venue)",
        "Directors / Members Present",
        "Quorum Confirmation",
        "Chairperson Appointment",
        "Resolution Preamble (WHEREAS)",
        "Operative Resolution (RESOLVED THAT)",
        "Authorization & Delegation",
        "Regulatory Filing Requirements",
        "Closing & Adjournment",
        "Signature Block — Chairperson & Directors",
    ],
};
