import type { DocumentTemplate } from "@/types";

export const breachNoticeTemplate: DocumentTemplate = {
    type: "breach-notice",
    label: "Breach Notice",
    description:
        "Notify a party of contract breach with cure period, consequences, and legal references.",
    isTwoParty: true,
    fields: [
        {
            name: "contractTitle",
            label: "Contract / Agreement Title",
            type: "text",
            placeholder: "e.g. Software Development Agreement dated 01-Mar-2025",
            required: true,
        },
        {
            name: "contractDate",
            label: "Contract Date",
            type: "date",
            required: true,
        },
        {
            name: "breachType",
            label: "Nature of Breach",
            type: "select",
            required: true,
            options: [
                { label: "Non-Payment", value: "non-payment" },
                { label: "Non-Performance / Delivery Failure", value: "non-performance" },
                { label: "Confidentiality Violation", value: "confidentiality" },
                { label: "IP Infringement", value: "ip-violation" },
                { label: "Material Misrepresentation", value: "misrepresentation" },
                { label: "Non-Compete Violation", value: "non-compete" },
                { label: "SLA Breach", value: "sla-breach" },
                { label: "Other Contractual Violation", value: "other" },
            ],
        },
        {
            name: "breachDescription",
            label: "Detailed Description of Breach",
            type: "textarea",
            placeholder: "Describe exactly what happened, when, and which contract clause was violated.",
            required: true,
        },
        {
            name: "contractClauseRef",
            label: "Violated Clause Reference",
            type: "text",
            placeholder: "e.g. Clause 7.2 (Payment Terms), Clause 12 (Confidentiality)",
            required: true,
        },
        {
            name: "curePeriod",
            label: "Cure Period",
            type: "select",
            required: true,
            options: [
                { label: "7 Days", value: "7" },
                { label: "15 Days", value: "15" },
                { label: "30 Days", value: "30" },
                { label: "No Cure — Immediate Termination", value: "none" },
            ],
            description: "Time given to the breaching party to remedy the breach.",
        },
        {
            name: "damagesAmount",
            label: "Damages / Losses Claimed (if applicable)",
            type: "text",
            placeholder: "e.g. ₹10,00,000",
            required: false,
        },
        {
            name: "previousReminders",
            label: "Previous Communications / Reminders",
            type: "textarea",
            placeholder: "e.g. Email dated 15-Jan-2025, Phone call on 20-Jan-2025...",
            required: false,
            description: "Reference prior attempts to resolve the issue.",
        },
        {
            name: "includeTermination",
            label: "Include Termination Warning?",
            type: "checkbox",
            required: false,
            description: "Warn that failure to cure will result in contract termination.",
        },
        {
            name: "includeDamagesClaim",
            label: "Include Damages / Compensation Demand?",
            type: "checkbox",
            required: false,
        },
        {
            name: "includeLegalProceedings",
            label: "Include Legal Proceedings Warning?",
            type: "checkbox",
            required: false,
            description: "Warn about potential legal action (arbitration or court proceedings).",
        },
    ],
    defaultClauses: [
        "Notice Header — BREACH NOTICE",
        "Parties Identification",
        "Contract Reference",
        "Nature of Breach",
        "Detailed Description of Non-Compliance",
        "Violated Clause Reference",
        "Cure Period & Required Remedy",
        "Consequences of Failure to Cure",
        "Damages / Losses (if applicable)",
        "Previous Communications Reference",
        "Reservation of Rights",
        "Signatory & Date",
    ],
};
