import type { DocumentTemplate } from "@/types";

export const coFounderAgreementTemplate: DocumentTemplate = {
    type: "co-founder-agreement",
    label: "Co-Founder Agreement",
    description:
        "Define equity split, vesting, roles, IP ownership, and exit terms between co-founders.",
    isTwoParty: true,
    fields: [
        {
            name: "startupName",
            label: "Startup / Company Name",
            type: "text",
            placeholder: "e.g. Acme Technologies Pvt Ltd",
            required: true,
        },
        {
            name: "cin",
            label: "CIN (if incorporated)",
            type: "text",
            placeholder: "e.g. U72200KA2023PTC175432",
            required: false,
        },
        {
            name: "businessDescription",
            label: "Nature of Business",
            type: "textarea",
            placeholder: "Describe what the startup does — product, market, and innovation.",
            required: true,
        },
        {
            name: "equitySplit",
            label: "Equity Split",
            type: "text",
            placeholder: "e.g. Founder A: 60%, Founder B: 40%",
            required: true,
            description: "Percentage equity each co-founder holds at inception.",
        },
        {
            name: "vestingSchedule",
            label: "Vesting Schedule",
            type: "select",
            required: true,
            options: [
                { label: "4 years, 1-year cliff, monthly vesting", value: "4y-1c-monthly" },
                { label: "4 years, 1-year cliff, quarterly vesting", value: "4y-1c-quarterly" },
                { label: "3 years, 1-year cliff, monthly vesting", value: "3y-1c-monthly" },
                { label: "No vesting (immediate full ownership)", value: "none" },
            ],
            description: "Reverse vesting protects the company if a founder leaves early.",
        },
        {
            name: "roleFounderA",
            label: "Founder A — Role & Responsibilities",
            type: "textarea",
            placeholder: "e.g. CEO — business strategy, fundraising, investor relations, hiring",
            required: true,
        },
        {
            name: "roleFounderB",
            label: "Founder B — Role & Responsibilities",
            type: "textarea",
            placeholder: "e.g. CTO — product development, engineering, tech architecture",
            required: true,
        },
        {
            name: "salaryTerms",
            label: "Founder Salary / Compensation",
            type: "text",
            placeholder: "e.g. No salary until Series A / ₹50,000/month each",
            required: false,
            description: "Many early-stage founders take no salary initially.",
        },
        {
            name: "decisionMaking",
            label: "Decision-Making Framework",
            type: "select",
            required: true,
            options: [
                { label: "Unanimous consent required", value: "unanimous" },
                { label: "Majority vote (by equity %)", value: "majority" },
                { label: "Domain-based (each founder decides in their area)", value: "domain" },
            ],
        },
        {
            name: "deadlockResolution",
            label: "Deadlock Resolution",
            type: "select",
            required: true,
            options: [
                { label: "Mediation, then Arbitration", value: "mediation-arbitration" },
                { label: "Independent advisor / mentor casts deciding vote", value: "advisor" },
                { label: "Shotgun clause (buy-sell)", value: "shotgun" },
            ],
        },
        {
            name: "nonCompetePeriod",
            label: "Non-Compete Period (During + Post-Exit)",
            type: "select",
            required: true,
            options: [
                { label: "During association only", value: "during-only" },
                { label: "During + 12 months post-exit", value: "12-months" },
                { label: "During + 24 months post-exit", value: "24-months" },
            ],
            description: "Post-exit non-compete may be unenforceable under S.27, Indian Contract Act.",
        },
        {
            name: "exitTriggers",
            label: "Exit / Departure Triggers",
            type: "textarea",
            placeholder: "e.g. Voluntary exit, termination for cause, disability, death, mutual agreement",
            required: false,
        },
        {
            name: "includeIPAssignment",
            label: "Include IP Assignment to Company?",
            type: "checkbox",
            required: false,
            description: "All IP created by founders is assigned to the company entity.",
        },
        {
            name: "includeAntiDilution",
            label: "Include Anti-Dilution Protection?",
            type: "checkbox",
            required: false,
            description: "Protect founders from excessive dilution in future rounds.",
        },
        {
            name: "includeExpensePolicy",
            label: "Include Expense Reimbursement Terms?",
            type: "checkbox",
            required: false,
        },
        {
            name: "jurisdiction",
            label: "Jurisdiction",
            type: "text",
            placeholder: "e.g. Bangalore",
            required: true,
        },
    ],
    defaultClauses: [
        "Preamble & Recitals",
        "Definitions",
        "Business Purpose & Objectives",
        "Roles & Responsibilities",
        "Equity Ownership & Split",
        "Vesting Schedule & Cliff",
        "Decision-Making Framework",
        "Intellectual Property Assignment",
        "Confidentiality Obligations",
        "Non-Compete & Non-Solicitation",
        "Founder Compensation & Expenses",
        "Deadlock Resolution Mechanism",
        "Exit & Departure Terms",
        "Transfer Restrictions (ROFR/ROFO)",
        "Anti-Dilution Protection",
        "Termination & Dissolution",
        "Governing Law & Dispute Resolution",
        "Signature Block",
    ],
};
