import type { DocumentTemplate } from "@/types";

export const consultancyAgreementTemplate: DocumentTemplate = {
    type: "consultancy-agreement",
    label: "Consultancy Agreement",
    description:
        "Engage freelancers and consultants with clear scope, IP ownership, payment terms, and TDS compliance.",
    isTwoParty: true,
    fields: [
        {
            name: "consultantType",
            label: "Consultant Type",
            type: "select",
            required: true,
            options: [
                { label: "Individual Freelancer", value: "individual" },
                { label: "Consulting Firm / Agency", value: "firm" },
                { label: "Technical Advisor", value: "advisor" },
                { label: "Domain Expert / SME", value: "sme" },
            ],
        },
        {
            name: "scopeOfWork",
            label: "Scope of Work",
            type: "textarea",
            placeholder: "Describe deliverables, milestones, and expected outcomes in detail.",
            required: true,
        },
        {
            name: "engagementDuration",
            label: "Engagement Duration",
            type: "select",
            required: true,
            options: [
                { label: "1 Month", value: "1-month" },
                { label: "3 Months", value: "3-months" },
                { label: "6 Months", value: "6-months" },
                { label: "12 Months", value: "12-months" },
                { label: "Project-based (no fixed term)", value: "project-based" },
            ],
        },
        {
            name: "consultancyFee",
            label: "Consultancy Fee",
            type: "text",
            placeholder: "e.g. ₹2,00,000 total / ₹50,000 per month",
            required: true,
        },
        {
            name: "paymentTerms",
            label: "Payment Terms",
            type: "select",
            required: true,
            options: [
                { label: "Monthly on invoice", value: "monthly" },
                { label: "Milestone-based", value: "milestone" },
                { label: "50% advance + 50% on completion", value: "advance-completion" },
                { label: "On completion", value: "completion" },
            ],
        },
        {
            name: "tdsRate",
            label: "TDS Rate Applicable",
            type: "select",
            required: true,
            options: [
                { label: "10% — S.194J (Professional/Technical)", value: "10-194j" },
                { label: "2% — S.194C (Contractor — Company/Firm)", value: "2-194c-company" },
                { label: "1% — S.194C (Contractor — Individual/HUF)", value: "1-194c-individual" },
                { label: "No TDS (below threshold)", value: "none" },
            ],
            description: "TDS must be deducted at source and deposited with the government.",
        },
        {
            name: "workLocation",
            label: "Work Location",
            type: "text",
            placeholder: "e.g. Remote / Company office / Hybrid",
            required: false,
        },
        {
            name: "noticePeriod",
            label: "Termination Notice Period",
            type: "select",
            required: true,
            options: [
                { label: "7 Days", value: "7-days" },
                { label: "15 Days", value: "15-days" },
                { label: "30 Days", value: "30-days" },
            ],
        },
        {
            name: "includeIPAssignment",
            label: "Include IP Assignment to Company?",
            type: "checkbox",
            required: false,
            description: "All work product, code, designs, and IP belong exclusively to the company.",
        },
        {
            name: "includeNDA",
            label: "Include Confidentiality / NDA?",
            type: "checkbox",
            required: false,
        },
        {
            name: "includeNonSolicit",
            label: "Include Non-Solicitation?",
            type: "checkbox",
            required: false,
            description: "Prevent consultant from poaching employees or clients during and after engagement.",
        },
        {
            name: "includeNonCompete",
            label: "Include Non-Compete (During Engagement)?",
            type: "checkbox",
            required: false,
            description: "Restrict competing work during the engagement period only.",
        },
        {
            name: "includeIndemnity",
            label: "Include Indemnification?",
            type: "checkbox",
            required: false,
        },
        {
            name: "additionalTerms",
            label: "Additional Terms",
            type: "textarea",
            placeholder: "e.g. Weekly standup calls, access requirements, travel reimbursement...",
            required: false,
        },
    ],
    defaultClauses: [
        "Agreement Header & Date",
        "Definitions",
        "Engagement Terms & Duration",
        "Scope of Work & Deliverables",
        "Consultancy Fee & Payment Terms",
        "Tax Deduction at Source (TDS)",
        "Independent Contractor Status",
        "Intellectual Property Assignment",
        "Confidentiality & Non-Disclosure",
        "Non-Solicitation",
        "Non-Compete (During Engagement)",
        "Representations & Warranties",
        "Indemnification",
        "Term & Termination",
        "Consequences of Termination",
        "Governing Law & Dispute Resolution",
        "Entire Agreement & Amendment",
        "Signature Block",
    ],
};
