import type { DocumentTemplate } from "@/types";

export const esopGrantTemplate: DocumentTemplate = {
    type: "esop-grant",
    label: "ESOP Grant Letter",
    description:
        "Draft an ESOP grant letter with vesting schedule, cliff period, exercise price, and exit terms.",
    isTwoParty: false,
    fields: [
        {
            name: "employeeName",
            label: "Employee / Grantee Name",
            type: "text",
            placeholder: "e.g. Priya Sharma",
            required: true,
        },
        {
            name: "employeeId",
            label: "Employee ID",
            type: "text",
            placeholder: "e.g. EMP-2023-042",
            required: false,
        },
        {
            name: "designation",
            label: "Designation",
            type: "text",
            placeholder: "e.g. Lead Engineer",
            required: true,
        },
        {
            name: "grantDate",
            label: "Grant Date",
            type: "date",
            required: true,
        },
        {
            name: "numberOfOptions",
            label: "Number of Options Granted",
            type: "text",
            placeholder: "e.g. 10,000",
            required: true,
        },
        {
            name: "exercisePrice",
            label: "Exercise Price per Option (₹)",
            type: "text",
            placeholder: "e.g. ₹10 (Face Value)",
            required: true,
            description: "Price at which the employee can buy shares. Often face value for early-stage startups.",
        },
        {
            name: "currentFMV",
            label: "Current Fair Market Value per Share (₹)",
            type: "text",
            placeholder: "e.g. ₹250",
            required: false,
            description: "FMV as per latest valuation report — required for tax computation under S.17(2) of IT Act.",
        },
        {
            name: "vestingSchedule",
            label: "Vesting Schedule",
            type: "select",
            required: true,
            options: [
                { label: "4 years, 1-year cliff, monthly vesting", value: "4y-1c-monthly" },
                { label: "4 years, 1-year cliff, quarterly vesting", value: "4y-1c-quarterly" },
                { label: "3 years, 1-year cliff, monthly vesting", value: "3y-1c-monthly" },
                { label: "4 years, no cliff, monthly vesting", value: "4y-0c-monthly" },
                { label: "Custom (describe in additional terms)", value: "custom" },
            ],
            description: "Standard startup vesting: 4 years with 1-year cliff.",
        },
        {
            name: "exerciseWindow",
            label: "Post-Termination Exercise Window",
            type: "select",
            required: true,
            options: [
                { label: "30 Days", value: "30-days" },
                { label: "90 Days", value: "90-days" },
                { label: "6 Months", value: "6-months" },
                { label: "12 Months", value: "12-months" },
            ],
            description: "Time after leaving the company to exercise vested options.",
        },
        {
            name: "esopPlanName",
            label: "ESOP Plan Name",
            type: "text",
            placeholder: "e.g. Acme Corp ESOP 2024",
            required: true,
        },
        {
            name: "boardResolutionDate",
            label: "Board Resolution Date",
            type: "date",
            required: false,
            description: "Date of board resolution approving the ESOP pool.",
        },
        {
            name: "includeAcceleration",
            label: "Include Acceleration on Exit?",
            type: "checkbox",
            required: false,
            description: "Single/double trigger acceleration on acquisition or IPO.",
        },
        {
            name: "includeTaxNote",
            label: "Include Tax Implications Note?",
            type: "checkbox",
            required: false,
            description: "Reference perquisite tax (S.17(2) IT Act), capital gains on sale, and startup ESOP deferral (S.80-IAC).",
        },
        {
            name: "additionalTerms",
            label: "Additional Terms",
            type: "textarea",
            placeholder: "e.g. Performance-based vesting conditions, lock-in period post-exercise...",
            required: false,
        },
    ],
    defaultClauses: [
        "Grant Letter Header & Date",
        "Grantee Identification",
        "Grant of Options (Number & Plan Reference)",
        "Exercise Price",
        "Vesting Schedule & Cliff",
        "Exercise Procedure",
        "Post-Termination Exercise Window",
        "Tax Implications",
        "Transfer Restrictions",
        "Accelerated Vesting (if applicable)",
        "Governing ESOP Plan Terms",
        "Confidentiality of Grant",
        "Acceptance & Signature Block",
    ],
};
