import type { DocumentTemplate } from "@/types";

export const experienceLetterTemplate: DocumentTemplate = {
    type: "experience-letter",
    label: "Experience Letter",
    description:
        "Provide a professional experience certificate detailing role, responsibilities, and tenure.",
    isTwoParty: false,
    fields: [
        {
            name: "employeeName",
            label: "Employee's Full Name",
            type: "text",
            placeholder: "e.g. Priya Sharma",
            required: true,
        },
        {
            name: "employeeId",
            label: "Employee ID",
            type: "text",
            placeholder: "e.g. EMP-2022-018",
            required: false,
        },
        {
            name: "designation",
            label: "Last Held Designation",
            type: "text",
            placeholder: "e.g. Senior Product Manager",
            required: true,
        },
        {
            name: "department",
            label: "Department",
            type: "text",
            placeholder: "e.g. Product",
            required: true,
        },
        {
            name: "dateOfJoining",
            label: "Date of Joining",
            type: "date",
            required: true,
        },
        {
            name: "lastWorkingDate",
            label: "Last Working Date",
            type: "date",
            required: true,
        },
        {
            name: "designationsHeld",
            label: "Designations Held (if promoted)",
            type: "textarea",
            placeholder: "e.g. 1. Software Engineer (Mar 2022 – Feb 2023)\n2. Senior Software Engineer (Mar 2023 – Nov 2024)\n3. Lead Engineer (Dec 2024 – Present)",
            required: false,
            description: "List all designations if the employee was promoted during tenure.",
        },
        {
            name: "keyResponsibilities",
            label: "Key Responsibilities & Achievements",
            type: "textarea",
            placeholder: "Describe the employee's core responsibilities, key projects, and notable achievements.",
            required: true,
        },
        {
            name: "performanceRemark",
            label: "Performance / Conduct Remark",
            type: "select",
            required: true,
            options: [
                { label: "Outstanding — Exceeded expectations consistently", value: "outstanding" },
                { label: "Excellent — Consistently met and often exceeded expectations", value: "excellent" },
                { label: "Good — Met expectations reliably", value: "good" },
                { label: "Satisfactory — Met basic requirements", value: "satisfactory" },
            ],
        },
        {
            name: "includeProjects",
            label: "Include Notable Projects Section?",
            type: "checkbox",
            required: false,
            description: "Add a section highlighting specific projects or contributions.",
        },
        {
            name: "includeSkills",
            label: "Include Skills & Competencies?",
            type: "checkbox",
            required: false,
        },
        {
            name: "includeWishNote",
            label: "Include Best Wishes Note?",
            type: "checkbox",
            required: false,
            description: "Add a closing note wishing the employee well in future endeavours.",
        },
    ],
    defaultClauses: [
        "Letterhead & Date",
        "\"To Whom It May Concern\" Header",
        "Employee Details & Tenure",
        "Designation History",
        "Role & Responsibilities",
        "Key Achievements / Projects",
        "Skills & Competencies",
        "Performance & Conduct Remark",
        "Best Wishes",
        "Signature — HR Head / Director",
    ],
};
