import type { DocumentTemplate } from "@/types";

export const gstBankLetterTemplate: DocumentTemplate = {
    type: "gst-bank-letter",
    label: "GST / Bank Letter",
    description:
        "Generate a letter for GST registration, current account opening, or bank-related compliance.",
    isTwoParty: false,
    fields: [
        {
            name: "letterPurpose",
            label: "Purpose of Letter",
            type: "select",
            required: true,
            options: [
                { label: "Current Account Opening", value: "current-account" },
                { label: "GST Registration Application", value: "gst-registration" },
                { label: "GST Cancellation / Amendment", value: "gst-amendment" },
                { label: "Bank Reference Letter", value: "bank-reference" },
                { label: "Address Proof for GST", value: "address-proof" },
                { label: "NOC from Landlord (for GST/Bank)", value: "noc-landlord" },
                { label: "Letter to Bank for Loan / OD Facility", value: "loan-request" },
            ],
            description: "Type of correspondence determines required details.",
        },
        {
            name: "companyName",
            label: "Company Name",
            type: "text",
            placeholder: "e.g. Acme Technologies Pvt Ltd",
            required: true,
        },
        {
            name: "cin",
            label: "CIN / LLP Identification Number",
            type: "text",
            placeholder: "e.g. U72200KA2023PTC12345",
            required: false,
        },
        {
            name: "gstin",
            label: "GSTIN (if already registered)",
            type: "text",
            placeholder: "e.g. 29AABCA1234F1ZA",
            required: false,
        },
        {
            name: "pan",
            label: "PAN",
            type: "text",
            placeholder: "e.g. AABCA1234F",
            required: true,
        },
        {
            name: "registeredAddress",
            label: "Registered / Principal Place of Business",
            type: "textarea",
            placeholder: "Full address including PIN code",
            required: true,
        },
        {
            name: "bankName",
            label: "Bank Name & Branch",
            type: "text",
            placeholder: "e.g. HDFC Bank, Koramangala Branch, Bangalore",
            required: false,
        },
        {
            name: "accountNumber",
            label: "Account Number (if existing)",
            type: "text",
            placeholder: "e.g. 50200012345678",
            required: false,
        },
        {
            name: "authorizedSignatory",
            label: "Authorized Signatory",
            type: "text",
            placeholder: "e.g. Rajesh Kumar, Director",
            required: true,
        },
        {
            name: "directorsList",
            label: "Directors / Partners List",
            type: "textarea",
            placeholder: "e.g. 1. Rajesh Kumar (DIN: 12345678) 2. Priya Sharma (DIN: 87654321)",
            required: false,
            description: "Required for current account opening and GST registration.",
        },
        {
            name: "natureOfBusiness",
            label: "Nature of Business (HSN/SAC Code if known)",
            type: "textarea",
            placeholder: "e.g. Software Development Services (SAC: 998314)",
            required: false,
        },
        {
            name: "expectedTurnover",
            label: "Expected Annual Turnover",
            type: "text",
            placeholder: "e.g. ₹50,00,000",
            required: false,
        },
        {
            name: "enclosedDocuments",
            label: "List of Enclosed Documents",
            type: "textarea",
            placeholder: "e.g. 1. Certificate of Incorporation 2. PAN Card 3. Board Resolution 4. Address Proof...",
            required: false,
        },
    ],
    defaultClauses: [
        "Letter Header & Date",
        "Addressee (Bank Manager / GST Officer)",
        "Subject Line",
        "Company Details (Name, CIN, PAN)",
        "Purpose of Application",
        "Business Description",
        "Director / Partner Details",
        "Address & Place of Business",
        "Expected Transaction Volume / Turnover",
        "Enclosed Documents List",
        "Declaration & Undertaking",
        "Signatory & Company Seal",
    ],
};
