import type { DocumentTemplate } from "@/types";

export const internshipCertTemplate: DocumentTemplate = {
    type: "internship-cert",
    label: "Internship Certificate",
    description:
        "Generate a formal internship completion certificate with all required details.",
    isTwoParty: false,
    fields: [
        // 1. Certificate Header
        {
            name: "certificateTitle",
            label: "Certificate Title",
            type: "select",
            required: true,
            options: [
                { label: "Certificate of Internship", value: "internship" },
                { label: "Certificate of Completion", value: "completion" },
                { label: "Internship Experience Certificate", value: "experience" },
                { label: "Certificate of Training", value: "training" },
            ],
            description: "The main title displayed on the certificate.",
        },
        {
            name: "certificateNumber",
            label: "Certificate Number",
            type: "text",
            placeholder: "e.g., INT-2026-042, CERT-001234",
            required: false,
            description: "Unique identifier for this certificate.",
        },

        // 2. Intern Information
        {
            name: "internName",
            label: "Intern Full Name",
            type: "text",
            placeholder: "e.g., Priya Sharma",
            required: true,
        },
        {
            name: "internId",
            label: "Intern ID / Roll Number / Registration Number",
            type: "text",
            placeholder: "e.g., INT-2026-042, ROLL12345",
            required: false,
        },
        {
            name: "internEmail",
            label: "Intern Email",
            type: "text",
            placeholder: "e.g., intern@example.com",
            required: false,
        },
        {
            name: "institution",
            label: "Educational Institution",
            type: "text",
            placeholder: "e.g., Indian Institute of Technology, Delhi",
            required: true,
            description: "The school/university the intern is attending.",
        },
        {
            name: "degreeProgram",
            label: "Degree / Program",
            type: "text",
            placeholder: "e.g., B.Tech Computer Science, MBA",
            required: false,
            description: "The degree program the intern is enrolled in.",
        },
        {
            name: "yearOfStudy",
            label: "Year of Study",
            type: "select",
            required: false,
            options: [
                { label: "1st Year", value: "1" },
                { label: "2nd Year", value: "2" },
                { label: "3rd Year", value: "3" },
                { label: "4th Year", value: "4" },
                { label: "Final Year", value: "final" },
                { label: "Not Applicable", value: "na" },
            ],
        },

        // 3. Internship Details
        {
            name: "internshipType",
            label: "Type of Internship",
            type: "select",
            required: true,
            options: [
                { label: "Full-time Internship", value: "full-time" },
                { label: "Part-time Internship", value: "part-time" },
                { label: "Summer Internship", value: "summer" },
                { label: "Winter Internship", value: "winter" },
                { label: "Research Internship", value: "research" },
                { label: "Remote/Virtual Internship", value: "remote" },
                { label: "Paid Internship", value: "paid" },
                { label: "Unpaid Internship", value: "unpaid" },
            ],
            description: "Category of the internship.",
        },
        {
            name: "department",
            label: "Department / Division",
            type: "text",
            placeholder: "e.g., Engineering, Marketing, Research & Development",
            required: true,
            description: "Which department the intern worked in.",
        },
        {
            name: "role",
            label: "Role / Designation",
            type: "text",
            placeholder: "e.g., Software Engineering Intern, Marketing Intern",
            required: true,
        },
        {
            name: "startDate",
            label: "Internship Start Date",
            type: "date",
            required: true,
        },
        {
            name: "endDate",
            label: "Internship End Date",
            type: "date",
            required: true,
        },
        {
            name: "duration",
            label: "Duration (calculated or specified)",
            type: "text",
            placeholder: "e.g., 3 months, 12 weeks, 6 months",
            required: false,
        },

        // 4. Project and Work Details
        {
            name: "projectTitle",
            label: "Project Title / Area",
            type: "text",
            placeholder: "e.g., Machine Learning for Customer Analytics",
            required: false,
            description: "The main project or area of work.",
        },
        {
            name: "projectDescription",
            label: "Project / Work Description",
            type: "textarea",
            placeholder:
                "Detailed description of the work, responsibilities, and projects undertaken...",
            required: true,
            description: "Comprehensive overview of the intern's work.",
        },
        {
            name: "skillsDeveloped",
            label: "Skills and Technologies",
            type: "textarea",
            placeholder: "e.g., Python, React, Data Analysis, Project Management...",
            required: false,
            description: "Key skills and technologies the intern worked with.",
        },
        {
            name: "responsibilities",
            label: "Key Responsibilities",
            type: "textarea",
            placeholder: "List of main duties and responsibilities during the internship...",
            required: false,
        },

        // 5. Performance Assessment
        {
            name: "performance",
            label: "Overall Performance Rating",
            type: "select",
            required: true,
            options: [
                { label: "Outstanding", value: "outstanding" },
                { label: "Excellent", value: "excellent" },
                { label: "Very Good", value: "very-good" },
                { label: "Good", value: "good" },
                { label: "Satisfactory", value: "satisfactory" },
            ],
            description: "Overall performance evaluation.",
        },
        {
            name: "attendance",
            label: "Attendance / Punctuality",
            type: "select",
            required: false,
            options: [
                { label: "Excellent", value: "excellent" },
                { label: "Good", value: "good" },
                { label: "Satisfactory", value: "satisfactory" },
                { label: "Not Assessed", value: "na" },
            ],
        },
        {
            name: "teamwork",
            label: "Teamwork / Collaboration",
            type: "select",
            required: false,
            options: [
                { label: "Excellent", value: "excellent" },
                { label: "Good", value: "good" },
                { label: "Satisfactory", value: "satisfactory" },
                { label: "Not Assessed", value: "na" },
            ],
        },
        {
            name: "technicalSkills",
            label: "Technical Skills Assessment",
            type: "select",
            required: false,
            options: [
                { label: "Excellent", value: "excellent" },
                { label: "Good", value: "good" },
                { label: "Satisfactory", value: "satisfactory" },
                { label: "Not Assessed", value: "na" },
            ],
        },
        {
            name: "comments",
            label: "Additional Comments / Recommendation",
            type: "textarea",
            placeholder: "e.g., The intern showed exceptional dedication... Would highly recommend...",
            required: false,
            description: "Optional detailed feedback about the intern's performance.",
        },

        // 6. Stipend and Compensation
        {
            name: "stipendPaid",
            label: "Stipend / Compensation Paid?",
            type: "select",
            required: false,
            options: [
                { label: "Yes - Paid Internship", value: "yes" },
                { label: "No - Unpaid Internship", value: "no" },
                { label: "Token Amount / Honorarium", value: "token" },
            ],
        },
        {
            name: "stipendAmount",
            label: "Stipend Amount (if applicable)",
            type: "text",
            placeholder: "e.g., ₹10,000 per month",
            required: false,
        },

        // 7. Certificate Options
        {
            name: "issueDate",
            label: "Certificate Issue Date",
            type: "date",
            required: true,
        },
        {
            name: "includePhoto",
            label: "Include Intern Photo?",
            type: "checkbox",
            required: false,
            description: "Some certificates include a passport-size photo.",
        },
        {
            name: "includeQR",
            label: "Include Verification QR Code?",
            type: "checkbox",
            required: false,
            description: "QR code for online verification.",
        },
        {
            name: "includeLogo",
            label: "Include Organization Logo?",
            type: "checkbox",
            required: false,
            description: "Display the company/organization logo.",
        },
        {
            name: "certificateLanguage",
            label: "Certificate Language",
            type: "select",
            required: true,
            options: [
                { label: "English", value: "english" },
                { label: "Hindi", value: "hindi" },
                { label: "Bilingual (English + Hindi)", value: "bilingual" },
            ],
        },

        // 8. Signatory Details
        {
            name: "signatoryName",
            label: "Authorizing Signatory Name",
            type: "text",
            placeholder: "e.g., Dr. Suresh Kumar",
            required: true,
        },
        {
            name: "signatoryDesignation",
            label: "Signatory Designation",
            type: "text",
            placeholder: "e.g., Head of Department, CEO, HR Manager",
            required: true,
        },
        {
            name: "signatoryDepartment",
            label: "Signatory Department",
            type: "text",
            placeholder: "e.g., Human Resources, Engineering",
            required: false,
        },
        {
            name: "secondSignatory",
            label: "Second Signatory (optional)",
            type: "text",
            placeholder: "e.g., Name and designation of second signatory if required",
            required: false,
        },
        {
            name: "organizationSeal",
            label: "Include Organization Seal/Stamp?",
            type: "checkbox",
            required: false,
        },
    ],
    defaultClauses: [
        "Organization Letterhead",
        "Certificate Title and Number",
        "Intern Identification",
        "Educational Institution",
        "Internship Type and Period",
        "Department and Role",
        "Project Description",
        "Skills and Responsibilities",
        "Performance Assessment",
        "Stipend Information",
        "Issue Date",
        "Signatory Block",
        "Organization Seal",
        "Verification Details",
    ],
};
