import type { DocumentTemplate } from "@/types";

export const internshipLetterTemplate: DocumentTemplate = {
    type: "internship-letter",
    label: "Internship Offer Letter",
    description:
        "Offer a startup internship with stipend, project scope, mentor details, and PPO eligibility.",
    isTwoParty: false,
    fields: [
        {
            name: "internName",
            label: "Intern's Full Name",
            type: "text",
            placeholder: "e.g. Arjun Patel",
            required: true,
        },
        {
            name: "internAddress",
            label: "Intern's Address",
            type: "textarea",
            placeholder: "Full residential address",
            required: false,
        },
        {
            name: "collegeName",
            label: "College / University",
            type: "text",
            placeholder: "e.g. IIT Bombay",
            required: false,
        },
        {
            name: "designation",
            label: "Internship Role",
            type: "text",
            placeholder: "e.g. Software Engineering Intern",
            required: true,
        },
        {
            name: "department",
            label: "Department / Team",
            type: "text",
            placeholder: "e.g. Engineering — Backend Team",
            required: true,
        },
        {
            name: "projectDescription",
            label: "Project / Work Description",
            type: "textarea",
            placeholder: "Describe the intern's project, expected deliverables, and learning objectives.",
            required: true,
        },
        {
            name: "startDate",
            label: "Internship Start Date",
            type: "date",
            required: true,
        },
        {
            name: "duration",
            label: "Internship Duration",
            type: "select",
            required: true,
            options: [
                { label: "1 Month", value: "1-month" },
                { label: "2 Months", value: "2-months" },
                { label: "3 Months", value: "3-months" },
                { label: "6 Months", value: "6-months" },
            ],
        },
        {
            name: "stipend",
            label: "Monthly Stipend (₹)",
            type: "text",
            placeholder: "e.g. ₹25,000",
            required: true,
        },
        {
            name: "workLocation",
            label: "Work Location",
            type: "text",
            placeholder: "e.g. Bangalore (Remote / Hybrid / On-site)",
            required: true,
        },
        {
            name: "reportingTo",
            label: "Reporting Manager / Mentor",
            type: "text",
            placeholder: "e.g. Priya Sharma, Lead Engineer",
            required: true,
        },
        {
            name: "workingHours",
            label: "Working Hours",
            type: "text",
            placeholder: "e.g. 10:00 AM – 6:00 PM, Monday to Friday",
            required: false,
        },
        {
            name: "ppoEligible",
            label: "Pre-Placement Offer (PPO) Eligible?",
            type: "select",
            required: true,
            options: [
                { label: "Yes — based on performance review", value: "yes-performance" },
                { label: "Yes — guaranteed on completion", value: "yes-guaranteed" },
                { label: "No PPO for this internship", value: "no" },
            ],
        },
        {
            name: "includeNDA",
            label: "Include Confidentiality / NDA Clause?",
            type: "checkbox",
            required: false,
            description: "Intern must keep company information confidential.",
        },
        {
            name: "includeIPClause",
            label: "Include IP Assignment?",
            type: "checkbox",
            required: false,
            description: "Work product created during internship belongs to the company.",
        },
        {
            name: "includeCertificate",
            label: "Include Completion Certificate Promise?",
            type: "checkbox",
            required: false,
            description: "Company will issue an internship completion certificate.",
        },
    ],
    defaultClauses: [
        "Offer Header & Date",
        "Intern Details",
        "Internship Role & Department",
        "Project Description & Deliverables",
        "Duration & Schedule",
        "Stipend & Benefits",
        "Work Location",
        "Reporting Manager / Mentor",
        "Confidentiality & NDA",
        "IP Assignment",
        "Code of Conduct",
        "PPO Eligibility",
        "Completion Certificate",
        "Offer Acceptance Deadline",
        "Signature Block",
    ],
};
