import type { DocumentTemplate } from "@/types";

export const ipAssignmentTemplate: DocumentTemplate = {
    type: "ip-assignment",
    label: "IP Assignment Agreement",
    description:
        "Transfer intellectual property ownership from founders, employees, or contractors to the company.",
    isTwoParty: true,
    fields: [
        {
            name: "assignorType",
            label: "Assignor Type",
            type: "select",
            required: true,
            options: [
                { label: "Founder / Promoter", value: "founder" },
                { label: "Employee", value: "employee" },
                { label: "Contractor / Freelancer", value: "contractor" },
                { label: "Third-Party Developer / Agency", value: "third-party" },
            ],
            description: "Who is assigning the IP to the company?",
        },
        {
            name: "ipDescription",
            label: "Description of Intellectual Property",
            type: "textarea",
            placeholder: "Describe the IP being assigned — software code, designs, algorithms, inventions, brand assets, trade secrets, etc.",
            required: true,
        },
        {
            name: "ipType",
            label: "Type of IP",
            type: "select",
            required: true,
            options: [
                { label: "Software / Source Code", value: "software" },
                { label: "Patent / Invention", value: "patent" },
                { label: "Trademark / Brand", value: "trademark" },
                { label: "Design / Creative Work", value: "design" },
                { label: "Trade Secrets / Know-How", value: "trade-secret" },
                { label: "All IP (Comprehensive)", value: "comprehensive" },
            ],
        },
        {
            name: "creationContext",
            label: "When Was the IP Created?",
            type: "select",
            required: true,
            options: [
                { label: "Before company incorporation (founder IP)", value: "pre-incorporation" },
                { label: "During employment / engagement", value: "during-engagement" },
                { label: "Commissioned work (work-for-hire)", value: "commissioned" },
                { label: "Mix of pre and during engagement", value: "mixed" },
            ],
        },
        {
            name: "consideration",
            label: "Consideration / Payment",
            type: "text",
            placeholder: "e.g. ₹1 (nominal) / Equity grant / Part of employment terms / ₹5,00,000",
            required: true,
            description: "Valid consideration is required for enforceable assignment under Indian Contract Act.",
        },
        {
            name: "includeSourceCode",
            label: "Include Source Code Transfer?",
            type: "checkbox",
            required: false,
            description: "Assignor must hand over all source code, repositories, and documentation.",
        },
        {
            name: "includeMoralRightsWaiver",
            label: "Include Moral Rights Waiver?",
            type: "checkbox",
            required: false,
            description: "S.57 Copyright Act 1957 — moral rights (attribution, integrity) cannot be fully waived in India but can be contractually managed.",
        },
        {
            name: "includeWarranties",
            label: "Include Originality Warranties?",
            type: "checkbox",
            required: false,
            description: "Assignor warrants that the IP is original, non-infringing, and free of encumbrances.",
        },
        {
            name: "includeFurtherAssurance",
            label: "Include Further Assurance Clause?",
            type: "checkbox",
            required: false,
            description: "Assignor agrees to sign any future documents needed to perfect the IP transfer.",
        },
        {
            name: "includeNonAssertion",
            label: "Include Non-Assertion Clause?",
            type: "checkbox",
            required: false,
            description: "Assignor agrees not to assert any IP rights against the company.",
        },
        {
            name: "jurisdiction",
            label: "Jurisdiction",
            type: "text",
            placeholder: "e.g. Bangalore",
            required: true,
        },
    ],
    defaultClauses: [
        "Agreement Header & Date",
        "Recitals",
        "Definitions",
        "Description of Assigned IP",
        "Assignment & Transfer of Rights",
        "Consideration",
        "Moral Rights",
        "Representations & Warranties",
        "Non-Assertion Covenant",
        "Further Assurance",
        "Source Code & Documentation Handover",
        "Confidentiality",
        "Governing Law & Dispute Resolution",
        "Entire Agreement",
        "Signature Block",
    ],
};
