import type { DocumentTemplate } from "@/types";

export const legalNoticeTemplate: DocumentTemplate = {
    type: "legal-notice",
    label: "Legal Notice",
    description:
        "Send a formal legal notice under Section 80 CPC or general civil/commercial disputes.",
    isTwoParty: true,
    fields: [
        {
            name: "noticeType",
            label: "Type of Legal Notice",
            type: "select",
            required: true,
            options: [
                { label: "Section 80 CPC — Against Government Body", value: "s80-cpc" },
                { label: "Recovery of Dues / Money", value: "recovery" },
                { label: "Breach of Contract", value: "breach" },
                { label: "Defamation", value: "defamation" },
                { label: "Cheque Bounce (S.138 NI Act)", value: "cheque-bounce" },
                { label: "Property Dispute", value: "property" },
                { label: "Consumer Complaint", value: "consumer" },
                { label: "Intellectual Property Infringement", value: "ip-infringement" },
                { label: "Employment Dispute", value: "employment" },
                { label: "General — Other", value: "general" },
            ],
            description: "The type determines applicable laws and mandatory requirements.",
        },
        {
            name: "jurisdiction",
            label: "Jurisdiction (Courts at)",
            type: "select",
            required: true,
            options: [
                { label: "Mumbai", value: "Mumbai" },
                { label: "Delhi", value: "Delhi" },
                { label: "Bangalore", value: "Bangalore" },
                { label: "Chennai", value: "Chennai" },
                { label: "Hyderabad", value: "Hyderabad" },
                { label: "Kolkata", value: "Kolkata" },
                { label: "Pune", value: "Pune" },
                { label: "Ahmedabad", value: "Ahmedabad" },
            ],
        },
        {
            name: "factualBackground",
            label: "Factual Background",
            type: "textarea",
            placeholder: "Describe the facts: What happened? When? What was the agreement/relationship?",
            required: true,
            description: "Chronological facts that form the basis of the legal notice.",
        },
        {
            name: "grievance",
            label: "Specific Grievance",
            type: "textarea",
            placeholder: "What went wrong? How was the sender harmed?",
            required: true,
        },
        {
            name: "demandedRelief",
            label: "Relief / Action Demanded",
            type: "textarea",
            placeholder: "e.g. Payment of ₹5,00,000 within 15 days, Cease and desist from using trademark...",
            required: true,
            description: "Specific action you want the recipient to take.",
        },
        {
            name: "responseDeadline",
            label: "Response Deadline (Days)",
            type: "select",
            required: true,
            options: [
                { label: "7 Days", value: "7" },
                { label: "15 Days", value: "15" },
                { label: "30 Days", value: "30" },
                { label: "60 Days (S.80 CPC — Mandatory)", value: "60" },
            ],
        },
        {
            name: "amountClaimed",
            label: "Amount Claimed (if monetary)",
            type: "text",
            placeholder: "e.g. ₹5,00,000",
            required: false,
        },
        {
            name: "relevantDocuments",
            label: "Key Documents / Evidence Referenced",
            type: "textarea",
            placeholder: "e.g. Agreement dated 01-Jan-2025, Invoice INV-001, Email correspondence dated 15-Feb-2025...",
            required: false,
        },
        {
            name: "includeConsequences",
            label: "Include Legal Consequences Warning?",
            type: "checkbox",
            required: false,
            description: "Warn about civil suit, criminal complaint, or other legal proceedings.",
        },
        {
            name: "sendVia",
            label: "Mode of Sending Notice",
            type: "select",
            required: false,
            options: [
                { label: "Registered Post with AD", value: "rpad" },
                { label: "Speed Post", value: "speed-post" },
                { label: "Courier", value: "courier" },
                { label: "Email (with confirmation)", value: "email" },
            ],
        },
    ],
    defaultClauses: [
        "Notice Header — LEGAL NOTICE",
        "Sender (Noticee) Details",
        "Recipient (Noticee) Details",
        "Subject Line",
        "Factual Background",
        "Specific Grievance & Cause of Action",
        "Applicable Laws & Legal Provisions",
        "Demand / Relief Sought",
        "Deadline for Response",
        "Consequences of Non-Compliance",
        "Reservation of Rights",
        "Mode of Service",
        "Signatory & Advocate Details",
    ],
};
