import type { DocumentTemplate } from "@/types";

export const loiTemplate: DocumentTemplate = {
    type: "loi",
    label: "Letter of Intent",
    description:
        "Express intent for a deal, partnership, or investment with key terms and a binding/non-binding framework.",
    isTwoParty: true,
    fields: [
        {
            name: "loiType",
            label: "Type of LOI",
            type: "select",
            required: true,
            options: [
                { label: "Investment / Funding", value: "investment" },
                { label: "Acquisition / Merger", value: "acquisition" },
                { label: "Strategic Partnership", value: "partnership" },
                { label: "Vendor / Service Engagement", value: "vendor" },
                { label: "Real Estate / Lease", value: "real-estate" },
                { label: "Joint Venture", value: "joint-venture" },
            ],
        },
        {
            name: "dealSummary",
            label: "Deal Summary",
            type: "textarea",
            placeholder: "e.g. Party A intends to invest ₹2 Cr in Party B at a pre-money valuation of ₹10 Cr for 16.67% equity.",
            required: true,
            description: "Brief summary of the proposed transaction.",
        },
        {
            name: "keyTerms",
            label: "Key Commercial Terms",
            type: "textarea",
            placeholder: "e.g. Investment: ₹2 Cr | Valuation: ₹10 Cr pre-money | Instrument: CCPS | Board Seat: Yes",
            required: true,
        },
        {
            name: "exclusivityPeriod",
            label: "Exclusivity Period",
            type: "select",
            required: false,
            options: [
                { label: "No Exclusivity", value: "none" },
                { label: "30 Days", value: "30-days" },
                { label: "60 Days", value: "60-days" },
                { label: "90 Days", value: "90-days" },
            ],
            description: "Period during which parties won't negotiate with others for the same deal.",
        },
        {
            name: "dueDiligencePeriod",
            label: "Due Diligence Period",
            type: "select",
            required: false,
            options: [
                { label: "15 Days", value: "15-days" },
                { label: "30 Days", value: "30-days" },
                { label: "45 Days", value: "45-days" },
                { label: "60 Days", value: "60-days" },
            ],
        },
        {
            name: "bindingStatus",
            label: "Binding Status",
            type: "select",
            required: true,
            options: [
                { label: "Non-Binding (except confidentiality & exclusivity)", value: "non-binding" },
                { label: "Fully Binding", value: "binding" },
                { label: "Partially Binding (specify in additional terms)", value: "partial" },
            ],
            description: "Most LOIs are non-binding except for confidentiality and exclusivity clauses.",
        },
        {
            name: "targetClosingDate",
            label: "Target Closing Date",
            type: "date",
            required: false,
            description: "Expected date for completing the definitive agreement.",
        },
        {
            name: "conditionsPrecedent",
            label: "Conditions Precedent",
            type: "textarea",
            placeholder: "e.g. Satisfactory due diligence, board approvals, regulatory clearances...",
            required: false,
            description: "Conditions that must be met before the deal closes.",
        },
        {
            name: "jurisdiction",
            label: "Jurisdiction",
            type: "select",
            required: true,
            options: [
                { label: "Mumbai", value: "Mumbai" },
                { label: "Delhi", value: "Delhi" },
                { label: "Bangalore", value: "Bangalore" },
                { label: "Chennai", value: "Chennai" },
                { label: "Hyderabad", value: "Hyderabad" },
            ],
        },
        {
            name: "includeConfidentiality",
            label: "Include Confidentiality Clause?",
            type: "checkbox",
            required: false,
            description: "This is typically binding even in a non-binding LOI.",
        },
        {
            name: "includeBreakFee",
            label: "Include Break Fee / Walk-Away Fee?",
            type: "checkbox",
            required: false,
            description: "Penalty if a party walks away after signing the LOI.",
        },
    ],
    defaultClauses: [
        "LOI Header & Date",
        "Parties Identification",
        "Purpose & Intent",
        "Deal Summary & Key Terms",
        "Binding / Non-Binding Declaration",
        "Exclusivity Period",
        "Due Diligence",
        "Conditions Precedent",
        "Confidentiality (Binding)",
        "Timeline & Target Closing",
        "Costs & Expenses",
        "Break Fee (if applicable)",
        "Governing Law & Jurisdiction",
        "Expiry of LOI",
        "Signature Block",
    ],
};
