import type { DocumentTemplate } from "@/types";

export const offerLetterTemplate: DocumentTemplate = {
    type: "offer-letter",
    label: "Offer Letter",
    description:
        "Send a professional job offer with compensation, role details, and joining conditions — ready to sign.",
    isTwoParty: false,
    fields: [
        {
            name: "candidateName",
            label: "Candidate's Full Name",
            type: "text",
            placeholder: "e.g. Priya Sharma",
            required: true,
        },
        {
            name: "candidateAddress",
            label: "Candidate's Address",
            type: "textarea",
            placeholder: "Full residential address",
            required: false,
        },
        {
            name: "designation",
            label: "Designation / Job Title",
            type: "text",
            placeholder: "e.g. Senior Software Engineer",
            required: true,
        },
        {
            name: "department",
            label: "Department",
            type: "text",
            placeholder: "e.g. Engineering",
            required: true,
        },
        {
            name: "reportingTo",
            label: "Reporting Manager",
            type: "text",
            placeholder: "e.g. Rajesh Kumar, VP Engineering",
            required: false,
        },
        {
            name: "joiningDate",
            label: "Expected Joining Date",
            type: "date",
            required: true,
        },
        {
            name: "ctcAnnual",
            label: "Annual CTC (₹)",
            type: "text",
            placeholder: "e.g. ₹18,00,000",
            required: true,
            description: "Total cost to company per annum.",
        },
        {
            name: "ctcBreakdown",
            label: "CTC Breakdown (Optional)",
            type: "textarea",
            placeholder: "e.g. Basic: ₹7,50,000 | HRA: ₹3,00,000 | Special Allowance: ₹4,50,000 | PF: ₹1,80,000 | Gratuity: ₹1,20,000",
            required: false,
            description: "Break down into Basic, HRA, PF, Gratuity, Special Allowance etc.",
        },
        {
            name: "employmentType",
            label: "Employment Type",
            type: "select",
            required: true,
            options: [
                { label: "Full-time", value: "full-time" },
                { label: "Part-time", value: "part-time" },
                { label: "Contract", value: "contract" },
                { label: "Internship (Pre-Placement Offer)", value: "ppo" },
            ],
        },
        {
            name: "probationPeriod",
            label: "Probation Period",
            type: "select",
            required: true,
            options: [
                { label: "No Probation", value: "none" },
                { label: "3 Months", value: "3-months" },
                { label: "6 Months", value: "6-months" },
            ],
        },
        {
            name: "noticePeriod",
            label: "Notice Period",
            type: "select",
            required: true,
            options: [
                { label: "15 Days", value: "15-days" },
                { label: "1 Month", value: "1-month" },
                { label: "2 Months", value: "2-months" },
                { label: "3 Months", value: "3-months" },
            ],
        },
        {
            name: "workLocation",
            label: "Work Location",
            type: "text",
            placeholder: "e.g. Bangalore (Hybrid — 3 days office)",
            required: true,
        },
        {
            name: "offerValidUntil",
            label: "Offer Valid Until",
            type: "date",
            required: true,
            description: "Deadline for the candidate to accept the offer.",
        },
        {
            name: "includeEsop",
            label: "Include ESOP mention?",
            type: "checkbox",
            required: false,
            description: "Reference ESOP eligibility in the offer (details in separate ESOP grant letter).",
        },
        {
            name: "includeRelocation",
            label: "Include Relocation Assistance?",
            type: "checkbox",
            required: false,
        },
        {
            name: "includeJoiningBonus",
            label: "Include Joining Bonus?",
            type: "checkbox",
            required: false,
        },
        {
            name: "joiningBonusAmount",
            label: "Joining Bonus Amount (if applicable)",
            type: "text",
            placeholder: "e.g. ₹1,00,000",
            required: false,
        },
        {
            name: "additionalTerms",
            label: "Additional Terms or Conditions",
            type: "textarea",
            placeholder: "e.g. Background verification, document submission requirements...",
            required: false,
        },
    ],
    defaultClauses: [
        "Offer Header & Date",
        "Candidate Details",
        "Designation & Department",
        "Compensation (CTC Breakdown)",
        "Joining Date & Location",
        "Probation Period Terms",
        "Notice Period",
        "Employment Conditions",
        "Confidentiality & IP Assignment",
        "Background Verification",
        "Offer Acceptance Deadline",
        "Signature Block",
    ],
};
