import type { DocumentTemplate } from "@/types";

export const paymentReminderTemplate: DocumentTemplate = {
    type: "payment-reminder",
    label: "Payment Reminder",
    description:
        "Send a firm but professional payment follow-up referencing invoice, amount, and due date.",
    isTwoParty: false,
    fields: [
        {
            name: "recipientName",
            label: "Recipient Name / Company",
            type: "text",
            placeholder: "e.g. Zenith Solutions Pvt Ltd",
            required: true,
        },
        {
            name: "recipientAddress",
            label: "Recipient Address",
            type: "textarea",
            placeholder: "Full business address",
            required: false,
        },
        {
            name: "contactPerson",
            label: "Attention (Contact Person)",
            type: "text",
            placeholder: "e.g. Mr. Rahul Verma, Accounts Payable",
            required: false,
        },
        {
            name: "invoiceNumber",
            label: "Invoice Number",
            type: "text",
            placeholder: "e.g. INV-2025-0042",
            required: true,
        },
        {
            name: "invoiceDate",
            label: "Invoice Date",
            type: "date",
            required: true,
        },
        {
            name: "invoiceAmount",
            label: "Outstanding Amount (₹)",
            type: "text",
            placeholder: "e.g. ₹3,50,000",
            required: true,
        },
        {
            name: "originalDueDate",
            label: "Original Due Date",
            type: "date",
            required: true,
        },
        {
            name: "daysOverdue",
            label: "Days Overdue",
            type: "number",
            placeholder: "e.g. 30",
            required: false,
        },
        {
            name: "reminderLevel",
            label: "Reminder Level",
            type: "select",
            required: true,
            options: [
                { label: "First Reminder — Friendly", value: "first" },
                { label: "Second Reminder — Firm", value: "second" },
                { label: "Final Notice — Legal Warning", value: "final" },
            ],
            description: "Tone escalates with each level. Final notice references legal consequences.",
        },
        {
            name: "paymentMethod",
            label: "Preferred Payment Method",
            type: "textarea",
            placeholder: "e.g. NEFT to Account: 1234567890, IFSC: SBIN0001234, Payee: Acme Corp Pvt Ltd",
            required: false,
            description: "Bank details or UPI ID for payment.",
        },
        {
            name: "serviceDescription",
            label: "Services / Goods Delivered",
            type: "textarea",
            placeholder: "e.g. Web development services for Project Phoenix (Phase 2), delivered on 15-Jan-2025",
            required: true,
        },
        {
            name: "includeInterest",
            label: "Mention Late Payment Interest?",
            type: "checkbox",
            required: false,
            description: "Reference contractual interest on overdue payments (if applicable).",
        },
        {
            name: "interestRate",
            label: "Interest Rate (% p.a.)",
            type: "text",
            placeholder: "e.g. 18%",
            required: false,
        },
        {
            name: "includeLegalNotice",
            label: "Include Legal Escalation Warning?",
            type: "checkbox",
            required: false,
            description: "Warn that non-payment may result in legal proceedings.",
        },
    ],
    defaultClauses: [
        "Letter Header & Date",
        "Recipient Details",
        "Subject Line (Invoice Reference)",
        "Opening — Purpose of Reminder",
        "Invoice & Payment Details",
        "Services / Goods Reference",
        "Outstanding Amount & Due Date",
        "Payment Instructions",
        "Late Payment Consequences",
        "Request for Immediate Action",
        "Contact for Queries",
        "Closing & Signatory",
    ],
};
