import type { DocumentTemplate } from "@/types";

export const relievingLetterTemplate: DocumentTemplate = {
    type: "relieving-letter",
    label: "Relieving Letter",
    description:
        "Generate a clean relieving letter confirming an employee's exit, tenure, and clearance status.",
    isTwoParty: false,
    fields: [
        {
            name: "employeeName",
            label: "Employee's Full Name",
            type: "text",
            placeholder: "e.g. Anita Singh",
            required: true,
        },
        {
            name: "employeeId",
            label: "Employee ID",
            type: "text",
            placeholder: "e.g. EMP-2023-042",
            required: false,
        },
        {
            name: "designation",
            label: "Designation at Exit",
            type: "text",
            placeholder: "e.g. Senior Backend Engineer",
            required: true,
        },
        {
            name: "department",
            label: "Department",
            type: "text",
            placeholder: "e.g. Engineering",
            required: true,
        },
        {
            name: "dateOfJoining",
            label: "Date of Joining",
            type: "date",
            required: true,
        },
        {
            name: "lastWorkingDate",
            label: "Last Working Date",
            type: "date",
            required: true,
        },
        {
            name: "resignationDate",
            label: "Resignation Date",
            type: "date",
            required: true,
        },
        {
            name: "exitReason",
            label: "Reason for Exit",
            type: "select",
            required: true,
            options: [
                { label: "Voluntary Resignation", value: "resignation" },
                { label: "Mutual Separation", value: "mutual" },
                { label: "End of Contract", value: "contract-end" },
                { label: "Retirement", value: "retirement" },
            ],
        },
        {
            name: "noticePeriodServed",
            label: "Notice Period Served?",
            type: "select",
            required: true,
            options: [
                { label: "Yes — Full notice served", value: "full" },
                { label: "Partial — Bought out remaining", value: "partial-buyout" },
                { label: "Waived by company", value: "waived" },
            ],
        },
        {
            name: "clearanceStatus",
            label: "Clearance Status",
            type: "select",
            required: true,
            options: [
                { label: "All dues cleared", value: "cleared" },
                { label: "Pending — subject to final settlement", value: "pending" },
            ],
        },
        {
            name: "conductRemark",
            label: "Conduct & Performance Remark",
            type: "select",
            required: false,
            options: [
                { label: "Excellent — highly recommended", value: "excellent" },
                { label: "Good — performed well", value: "good" },
                { label: "Satisfactory", value: "satisfactory" },
                { label: "Neutral — no remarks", value: "neutral" },
            ],
        },
        {
            name: "includeExpCert",
            label: "Combine with Experience Certificate?",
            type: "checkbox",
            required: false,
            description: "Add a detailed experience certificate section to the relieving letter.",
        },
        {
            name: "includeNDAReminder",
            label: "Include Post-Employment NDA Reminder?",
            type: "checkbox",
            required: false,
            description: "Remind the employee of ongoing confidentiality obligations.",
        },
    ],
    defaultClauses: [
        "Relieving Letter Header & Date",
        "Employee Identification",
        "Tenure Confirmation",
        "Acceptance of Resignation",
        "Last Working Date",
        "Notice Period & Settlement",
        "Clearance & Dues",
        "Conduct & Performance Remark",
        "Post-Employment Obligations",
        "Good Wishes",
        "Signatory & Seal",
    ],
};
