import type { DocumentTemplate } from "@/types";

export const serviceAgreementTemplate: DocumentTemplate = {
    type: "service-agreement",
    label: "Service Agreement",
    description:
        "Define SaaS or service terms with SLAs, liability caps, data handling, and payment schedules.",
    isTwoParty: true,
    fields: [
        {
            name: "serviceType",
            label: "Type of Service",
            type: "select",
            required: true,
            options: [
                { label: "SaaS / Cloud Software", value: "saas" },
                { label: "IT Services / Development", value: "it-services" },
                { label: "Managed Services / Support", value: "managed-services" },
                { label: "Marketing / Creative Services", value: "marketing" },
                { label: "Professional / Advisory Services", value: "advisory" },
            ],
        },
        {
            name: "serviceDescription",
            label: "Service Description",
            type: "textarea",
            placeholder: "Describe the services in detail — features, scope, exclusions.",
            required: true,
        },
        {
            name: "pricingModel",
            label: "Pricing Model",
            type: "select",
            required: true,
            options: [
                { label: "Fixed fee (one-time)", value: "fixed" },
                { label: "Monthly subscription", value: "monthly" },
                { label: "Annual subscription", value: "annual" },
                { label: "Per-user / Per-seat pricing", value: "per-user" },
                { label: "Usage-based / Pay-as-you-go", value: "usage" },
                { label: "Milestone-based", value: "milestone" },
            ],
        },
        {
            name: "contractValue",
            label: "Contract Value / Fee",
            type: "text",
            placeholder: "e.g. ₹5,00,000/year or ₹25,000/month",
            required: true,
        },
        {
            name: "paymentTerms",
            label: "Payment Terms",
            type: "select",
            required: true,
            options: [
                { label: "Net 15 (15 days from invoice)", value: "net-15" },
                { label: "Net 30 (30 days from invoice)", value: "net-30" },
                { label: "Advance payment", value: "advance" },
                { label: "50% advance + 50% on delivery", value: "split" },
            ],
        },
        {
            name: "contractDuration",
            label: "Contract Duration",
            type: "select",
            required: true,
            options: [
                { label: "3 Months", value: "3-months" },
                { label: "6 Months", value: "6-months" },
                { label: "12 Months (1 Year)", value: "12-months" },
                { label: "24 Months (2 Years)", value: "24-months" },
                { label: "Month-to-month (auto-renew)", value: "month-to-month" },
            ],
        },
        {
            name: "slaUptime",
            label: "SLA — Uptime Guarantee",
            type: "select",
            required: false,
            options: [
                { label: "99.9% (8.7 hrs downtime/year)", value: "99.9" },
                { label: "99.5% (43.8 hrs downtime/year)", value: "99.5" },
                { label: "99% (87.6 hrs downtime/year)", value: "99" },
                { label: "No SLA", value: "none" },
            ],
            description: "Applicable mainly for SaaS / cloud / managed services.",
        },
        {
            name: "slaResponseTime",
            label: "SLA — Support Response Time",
            type: "text",
            placeholder: "e.g. P1: 1 hour, P2: 4 hours, P3: 24 hours",
            required: false,
        },
        {
            name: "liabilityCap",
            label: "Liability Cap",
            type: "select",
            required: true,
            options: [
                { label: "Equal to total fees paid in last 12 months", value: "12-month-fees" },
                { label: "Equal to total contract value", value: "total-value" },
                { label: "2x total fees paid", value: "2x-fees" },
                { label: "Unlimited liability", value: "unlimited" },
            ],
        },
        {
            name: "includeDataProtection",
            label: "Include Data Protection / DPA?",
            type: "checkbox",
            required: false,
            description: "Reference DPDP Act 2023 and IT Act 2000 data handling obligations.",
        },
        {
            name: "includeIPClause",
            label: "Include IP Ownership Clause?",
            type: "checkbox",
            required: false,
            description: "Specify who owns deliverables, custom work, and pre-existing IP.",
        },
        {
            name: "includeConfidentiality",
            label: "Include Confidentiality?",
            type: "checkbox",
            required: false,
        },
        {
            name: "includeForceMajeure",
            label: "Include Force Majeure?",
            type: "checkbox",
            required: false,
        },
        {
            name: "includeIndemnity",
            label: "Include Indemnification?",
            type: "checkbox",
            required: false,
        },
        {
            name: "disputeResolution",
            label: "Dispute Resolution",
            type: "select",
            required: true,
            options: [
                { label: "Arbitration (Arbitration & Conciliation Act 1996)", value: "arbitration" },
                { label: "Mediation first, then Arbitration", value: "mediation-arbitration" },
                { label: "Courts only", value: "courts" },
            ],
        },
    ],
    defaultClauses: [
        "Agreement Header & Date",
        "Definitions",
        "Service Description & Scope",
        "Service Level Agreement (SLA)",
        "Pricing & Payment Terms",
        "Taxes & GST Compliance",
        "Intellectual Property Ownership",
        "Data Protection & Privacy",
        "Confidentiality",
        "Representations & Warranties",
        "Limitation of Liability",
        "Indemnification",
        "Term & Renewal",
        "Termination",
        "Consequences of Termination",
        "Force Majeure",
        "Governing Law & Dispute Resolution",
        "General Provisions (Severability, Notices, Assignment)",
        "Entire Agreement",
        "Signature Block",
    ],
};
