import type { DocumentTemplate } from "@/types";

export const shareAllotmentTemplate: DocumentTemplate = {
    type: "share-allotment",
    label: "Share Allotment Letter",
    description:
        "Issue a board-resolution-ready share allotment letter for founders, investors, or ESOP holders.",
    isTwoParty: false,
    fields: [
        {
            name: "allotteeName",
            label: "Allottee Name",
            type: "text",
            placeholder: "e.g. Vikram Mehta / Seed Ventures LLP",
            required: true,
        },
        {
            name: "allotteeAddress",
            label: "Allottee Address",
            type: "textarea",
            placeholder: "Full address of the allottee",
            required: false,
        },
        {
            name: "allotteeType",
            label: "Allottee Type",
            type: "select",
            required: true,
            options: [
                { label: "Founder", value: "founder" },
                { label: "Angel Investor", value: "angel" },
                { label: "Institutional Investor (VC/PE)", value: "institutional" },
                { label: "ESOP Holder (Exercise)", value: "esop" },
                { label: "Employee (Sweat Equity)", value: "sweat-equity" },
            ],
        },
        {
            name: "numberOfShares",
            label: "Number of Shares",
            type: "text",
            placeholder: "e.g. 50,000",
            required: true,
        },
        {
            name: "shareType",
            label: "Type of Shares",
            type: "select",
            required: true,
            options: [
                { label: "Equity Shares", value: "equity" },
                { label: "Preference Shares (CCPS)", value: "ccps" },
                { label: "Preference Shares (CCD)", value: "ccd" },
                { label: "Sweat Equity Shares", value: "sweat-equity" },
            ],
        },
        {
            name: "faceValue",
            label: "Face Value per Share (₹)",
            type: "text",
            placeholder: "e.g. ₹10",
            required: true,
        },
        {
            name: "premiumPerShare",
            label: "Premium per Share (₹)",
            type: "text",
            placeholder: "e.g. ₹490",
            required: false,
            description: "Share premium above face value (if any).",
        },
        {
            name: "totalConsideration",
            label: "Total Consideration (₹)",
            type: "text",
            placeholder: "e.g. ₹25,00,000",
            required: true,
        },
        {
            name: "allotmentDate",
            label: "Date of Allotment",
            type: "date",
            required: true,
        },
        {
            name: "boardResolutionDate",
            label: "Board Resolution Date",
            type: "date",
            required: true,
            description: "Date of the board meeting approving this allotment.",
        },
        {
            name: "shareholdingPost",
            label: "Shareholding % Post-Allotment",
            type: "text",
            placeholder: "e.g. 5.2%",
            required: false,
        },
        {
            name: "paymentReceived",
            label: "Payment Status",
            type: "select",
            required: true,
            options: [
                { label: "Full payment received", value: "full" },
                { label: "Partial payment (calls in arrears)", value: "partial" },
                { label: "Against conversion (CCPS/CCD)", value: "conversion" },
                { label: "ESOP exercise (against exercise price)", value: "esop-exercise" },
            ],
        },
        {
            name: "includeROCFiling",
            label: "Reference ROC Filing (PAS-3)?",
            type: "checkbox",
            required: false,
            description: "Mention that Form PAS-3 will be filed with MCA within 15 days.",
        },
        {
            name: "includeShareCert",
            label: "Reference Share Certificate Issuance?",
            type: "checkbox",
            required: false,
            description: "Confirm share certificate will be issued within 2 months (S.56, Companies Act 2013).",
        },
    ],
    defaultClauses: [
        "Allotment Letter Header & Date",
        "Allottee Details",
        "Board Resolution Reference",
        "Share Details (Type, Number, Face Value, Premium)",
        "Total Consideration & Payment Status",
        "Shareholding Post-Allotment",
        "Rights Attached to Shares",
        "Transfer Restrictions (if any)",
        "ROC Filing & Compliance",
        "Share Certificate Issuance",
        "Signatory & Company Seal",
    ],
};
