import type { DocumentTemplate } from "@/types";

export const sponsorshipLetterTemplate: DocumentTemplate = {
    type: "sponsorship-letter",
    label: "Sponsorship Letter",
    description:
        "Create a compelling sponsorship request or confirmation letter.",
    isTwoParty: true,
    fields: [
        // 1. Event/Initiative Details
        {
            name: "eventName",
            label: "Event / Initiative Name",
            type: "text",
            placeholder: "e.g., TechFest 2026, Annual Startup Summit",
            required: true,
        },
        {
            name: "eventType",
            label: "Type of Event",
            type: "select",
            required: true,
            options: [
                { label: "Technology Conference", value: "tech-conference" },
                { label: "Cultural Festival", value: "cultural" },
                { label: "Sports Tournament", value: "sports" },
                { label: "Educational Workshop", value: "workshop" },
                { label: "Charity / Fundraiser", value: "charity" },
                { label: "Research Symposium", value: "symposium" },
                { label: "Hackathon", value: "hackathon" },
                { label: "Networking Event", value: "networking" },
                { label: "Award Ceremony", value: "awards" },
                { label: "Other", value: "other" },
            ],
            description: "Category of the event for appropriate tone and structure.",
        },
        {
            name: "eventDate",
            label: "Event Date / Period",
            type: "date",
            required: true,
        },
        {
            name: "eventEndDate",
            label: "Event End Date (if multi-day)",
            type: "date",
            required: false,
        },
        {
            name: "eventVenue",
            label: "Event Venue / Location",
            type: "text",
            placeholder: "e.g., Convention Center, Bangalore",
            required: false,
        },
        {
            name: "eventDescription",
            label: "Event Description",
            type: "textarea",
            placeholder:
                "Describe the event, its purpose, expected audience, and scale...",
            required: true,
            description: "Comprehensive description of the event.",
        },
        {
            name: "expectedAttendance",
            label: "Expected Attendance",
            type: "text",
            placeholder: "e.g., 500+ participants, 1000+ visitors",
            required: false,
            description: "Expected number of participants or attendees.",
        },
        {
            name: "targetAudience",
            label: "Target Audience",
            type: "textarea",
            placeholder: "e.g., Students, professionals, industry leaders, startups...",
            required: false,
            description: "Who will attend this event?",
        },

        // 2. Organizer Information
        {
            name: "organizerName",
            label: "Organizer / Host Organization",
            type: "text",
            placeholder: "e.g., ABC University, XYZ Foundation",
            required: true,
        },
        {
            name: "organizerDescription",
            label: "About the Organizer",
            type: "textarea",
            placeholder: "Brief background of the organizing institution...",
            required: false,
            description: "Background credibility of the organizer.",
        },
        {
            name: "organizerWebsite",
            label: "Organizer Website",
            type: "text",
            placeholder: "e.g., www.example.com",
            required: false,
        },
        {
            name: "previousEditions",
            label: "Previous Editions (if any)",
            type: "text",
            placeholder: "e.g., 5th edition, Successfully held since 2020...",
            required: false,
            description: "History and track record of the event.",
        },

        // 3. Sponsorship Details
        {
            name: "sponsorshipType",
            label: "Type of Sponsorship Requested",
            type: "select",
            required: true,
            options: [
                { label: "Title Sponsor", value: "title" },
                { label: "Platinum Sponsor", value: "platinum" },
                { label: "Gold Sponsor", value: "gold" },
                { label: "Silver Sponsor", value: "silver" },
                { label: "Bronze Sponsor", value: "bronze" },
                { label: "Event Partner", value: "partner" },
                { label: "In-Kind Sponsor (services/products)", value: "in-kind" },
                { label: "Media Partner", value: "media" },
                { label: "Custom Package", value: "custom" },
            ],
            description: "The sponsorship tier or type being requested.",
        },
        {
            name: "sponsorshipAmount",
            label: "Sponsorship Amount Requested (₹)",
            type: "text",
            placeholder: "e.g., ₹5,00,000, ₹10,00,000",
            required: false,
            description: "The financial contribution being requested (if monetary).",
        },
        {
            name: "inKindValue",
            label: "In-Kind Contribution Value (if applicable)",
            type: "text",
            placeholder: "e.g., Products/services worth ₹2,00,000",
            required: false,
            description: "For non-monetary sponsorships.",
        },
        {
            name: "fundsUsage",
            label: "How Funds Will Be Used",
            type: "textarea",
            placeholder: "Breakdown: Venue - ₹2L, Marketing - ₹1L, Prizes - ₹1L...",
            required: false,
            description: "Transparency about fund utilization.",
        },

        // 4. Sponsor Benefits
        {
            name: "brandVisibility",
            label: "Brand Visibility Benefits",
            type: "textarea",
            placeholder: "e.g., Logo on all marketing materials, website, banners...",
            required: true,
            description: "Marketing exposure the sponsor will receive.",
        },
        {
            name: "boothSpace",
            label: "Exhibition/Booth Space",
            type: "text",
            placeholder: "e.g., 10x10 feet booth, Premium location",
            required: false,
            description: "Physical presence opportunity at the event.",
        },
        {
            name: "speakingOpportunity",
            label: "Speaking Opportunity",
            type: "select",
            required: false,
            options: [
                { label: "Keynote speech", value: "keynote" },
                { label: "Panel discussion", value: "panel" },
                { label: "Welcome address", value: "welcome" },
                { label: "Presentation slot", value: "presentation" },
                { label: "None", value: "none" },
            ],
            description: "Opportunity for sponsor representatives to speak.",
        },
        {
            name: "networkingAccess",
            label: "VIP/Networking Access",
            type: "checkbox",
            required: false,
            description: "Include VIP passes or exclusive networking opportunities.",
        },
        {
            name: "mediaCoverage",
            label: "Media Coverage Benefits",
            type: "textarea",
            placeholder: "e.g., Sponsor mention in press releases, social media coverage...",
            required: false,
            description: "Media and PR benefits for the sponsor.",
        },
        {
            name: "logoPlacement",
            label: "Logo Placement Details",
            type: "textarea",
            placeholder: "Where will the sponsor logo appear? (Banners, website, merchandise...)",
            required: false,
        },
        {
            name: "additionalBenefits",
            label: "Additional Benefits",
            type: "textarea",
            placeholder: "Any other benefits not covered above...",
            required: false,
        },

        // 5. Audience Profile
        {
            name: "audienceDemographics",
            label: "Audience Demographics",
            type: "textarea",
            placeholder: "e.g., 60% students, 30% professionals, 10% executives...",
            required: false,
            description: "Breakdown of who will see the sponsor's brand.",
        },
        {
            name: "reach",
            label: "Expected Reach / Impressions",
            type: "text",
            placeholder: "e.g., 50,000+ social media impressions, 5000+ direct attendees",
            required: false,
            description: "Marketing reach statistics.",
        },

        // 6. Timeline
        {
            name: "sponsorshipDeadline",
            label: "Sponsorship Confirmation Deadline",
            type: "date",
            required: true,
            description: "By when does the sponsor need to confirm?",
        },
        {
            name: "paymentTerms",
            label: "Payment Terms",
            type: "select",
            required: false,
            options: [
                { label: "Full amount upfront", value: "upfront" },
                { label: "50% advance, 50% after event", value: "50-50" },
                { label: "Installments", value: "installments" },
                { label: "Within 30 days of invoice", value: "net-30" },
            ],
        },
        {
            name: "mouRequired",
            label: "Formal MOU/Agreement Required?",
            type: "checkbox",
            required: false,
            description: "Whether a formal agreement will be signed.",
        },

        // 7. Contact Information
        {
            name: "contactPerson",
            label: "Primary Contact Person",
            type: "text",
            placeholder: "e.g., John Smith",
            required: true,
        },
        {
            name: "contactDesignation",
            label: "Contact Designation",
            type: "text",
            placeholder: "e.g., Sponsorship Coordinator, Event Head",
            required: true,
        },
        {
            name: "contactEmail",
            label: "Contact Email",
            type: "text",
            placeholder: "e.g., sponsor@event.com",
            required: true,
        },
        {
            name: "contactPhone",
            label: "Contact Phone",
            type: "text",
            placeholder: "e.g., +91-9876543210",
            required: true,
        },
        {
            name: "alternateContact",
            label: "Alternate Contact (optional)",
            type: "text",
            placeholder: "Name and contact details...",
            required: false,
        },

        // 8. Letter Options
        {
            name: "letterType",
            label: "Type of Letter",
            type: "select",
            required: true,
            options: [
                { label: "Sponsorship Request", value: "request" },
                { label: "Sponsorship Confirmation/Thank You", value: "confirmation" },
                { label: "Sponsorship Proposal", value: "proposal" },
            ],
            description: "Whether this is a request or acknowledgment.",
        },
        {
            name: "letterTone",
            label: "Letter Tone",
            type: "select",
            required: true,
            options: [
                { label: "Professional / Formal", value: "formal" },
                { label: "Enthusiastic / Energetic", value: "enthusiastic" },
                { label: "Corporate / Business", value: "corporate" },
                { label: "Community-Focused", value: "community" },
            ],
        },
        {
            name: "includeBrochure",
            label: "Mention Attached Brochure?",
            type: "checkbox",
            required: false,
            description: "Reference to attached event brochure or prospectus.",
        },
        {
            name: "taxExemption",
            label: "Tax Exemption Available (80G)?",
            type: "checkbox",
            required: false,
            description: "For non-profit events with tax benefits for sponsors.",
        },

        // 9. Success Metrics
        {
            name: "pastSponsors",
            label: "Past Sponsors (if any)",
            type: "textarea",
            placeholder: "e.g., Previously sponsored by Google, Microsoft...",
            required: false,
            description: "Credibility through past partnerships.",
        },
        {
            name: "previousSuccess",
            label: "Previous Edition Success",
            type: "textarea",
            placeholder: "Highlights from previous editions...",
            required: false,
            description: "Evidence of successful past events.",
        },
    ],
    defaultClauses: [
        "Letterhead and Date",
        "Salutation",
        "Introduction and Greeting",
        "Event Overview",
        "Organizer Background",
        "Sponsorship Opportunity",
        "Sponsorship Benefits",
        "Audience Profile and Reach",
        "Brand Visibility Details",
        "Speaking/Networking Opportunities",
        "Financial Terms",
        "Timeline and Deadlines",
        "Contact Information",
        "Call to Action",
        "Closing and Thank You",
        "Signatory Block",
        "Attachments Reference",
    ],
};
