import type { DocumentTemplate } from "@/types";

export const startupIndiaTemplate: DocumentTemplate = {
    type: "startup-india",
    label: "Startup India Letter",
    description:
        "Draft a Startup India recognition application letter or DPIIT correspondence.",
    isTwoParty: false,
    fields: [
        {
            name: "letterPurpose",
            label: "Purpose of Letter",
            type: "select",
            required: true,
            options: [
                { label: "DPIIT Recognition Application", value: "dpiit-recognition" },
                { label: "Tax Exemption (Section 80-IAC)", value: "tax-exemption" },
                { label: "Angel Tax Exemption (S.56(2)(viib))", value: "angel-tax" },
                { label: "Self-Certification (Labour & Environment)", value: "self-certification" },
                { label: "IPR Fast-Track Application", value: "ipr-fasttrack" },
                { label: "Fund of Funds Application", value: "fund-of-funds" },
                { label: "General DPIIT Correspondence", value: "general" },
            ],
            description: "Different purposes have different mandatory requirements.",
        },
        {
            name: "companyName",
            label: "Company Name",
            type: "text",
            placeholder: "e.g. Acme Technologies Pvt Ltd",
            required: true,
        },
        {
            name: "cin",
            label: "CIN (Corporate Identification Number)",
            type: "text",
            placeholder: "e.g. U72200KA2023PTC12345",
            required: true,
        },
        {
            name: "dateOfIncorporation",
            label: "Date of Incorporation",
            type: "date",
            required: true,
        },
        {
            name: "registeredAddress",
            label: "Registered Address",
            type: "textarea",
            placeholder: "Full registered office address as per MCA records",
            required: true,
        },
        {
            name: "natureOfBusiness",
            label: "Nature of Business / Innovation",
            type: "textarea",
            placeholder: "Describe your product/service, innovation, and how it's scalable or creates IP.",
            required: true,
            description: "DPIIT requires proof that the entity works towards innovation, development, or improvement of products/services.",
        },
        {
            name: "turnover",
            label: "Annual Turnover (Last FY)",
            type: "text",
            placeholder: "e.g. ₹8,50,00,000",
            required: false,
            description: "Must be below ₹100 Cr for Startup India eligibility.",
        },
        {
            name: "numberOfEmployees",
            label: "Number of Employees",
            type: "text",
            placeholder: "e.g. 25",
            required: false,
        },
        {
            name: "dpiitNumber",
            label: "Existing DPIIT Recognition Number (if any)",
            type: "text",
            placeholder: "e.g. DIPP12345",
            required: false,
        },
        {
            name: "founderName",
            label: "Founder / Authorized Signatory",
            type: "text",
            placeholder: "e.g. Rajesh Kumar, CEO & Co-Founder",
            required: true,
        },
        {
            name: "includeFinancials",
            label: "Attach Financial Summary?",
            type: "checkbox",
            required: false,
            description: "Reference audited financials or CA-certified turnover statement.",
        },
        {
            name: "includePitchDeck",
            label: "Reference Pitch Deck / Business Plan?",
            type: "checkbox",
            required: false,
        },
    ],
    defaultClauses: [
        "Letter Header & Date",
        "Addressee (DPIIT / Registrar)",
        "Subject Line",
        "Company Identification (Name, CIN, Address)",
        "Date of Incorporation & Eligibility",
        "Nature of Business & Innovation",
        "Purpose of Application",
        "Turnover & Compliance Declaration",
        "List of Enclosed Documents",
        "Declaration & Undertaking",
        "Request for Consideration",
        "Signatory & Seal",
    ],
};
