import type { DocumentTemplate } from "@/types";

export const terminationLetterTemplate: DocumentTemplate = {
    type: "termination-letter",
    label: "Termination Letter",
    description:
        "Issue a compliant termination letter citing grounds, notice period, and final settlement details.",
    isTwoParty: false,
    fields: [
        {
            name: "employeeName",
            label: "Employee's Full Name",
            type: "text",
            placeholder: "e.g. Vikram Mehta",
            required: true,
        },
        {
            name: "employeeId",
            label: "Employee ID",
            type: "text",
            placeholder: "e.g. EMP-2023-015",
            required: false,
        },
        {
            name: "designation",
            label: "Designation",
            type: "text",
            placeholder: "e.g. Senior Backend Engineer",
            required: true,
        },
        {
            name: "department",
            label: "Department",
            type: "text",
            placeholder: "e.g. Engineering",
            required: true,
        },
        {
            name: "dateOfJoining",
            label: "Date of Joining",
            type: "date",
            required: true,
        },
        {
            name: "terminationReason",
            label: "Reason for Termination",
            type: "select",
            required: true,
            options: [
                { label: "Performance issues (PIP failure)", value: "performance" },
                { label: "Misconduct / Policy violation", value: "misconduct" },
                { label: "Redundancy / Role elimination", value: "redundancy" },
                { label: "Probation period failure", value: "probation-failure" },
                { label: "End of contract term", value: "contract-end" },
                { label: "Business closure / Shutdown", value: "business-closure" },
            ],
        },
        {
            name: "terminationDate",
            label: "Last Working Date / Effective Date",
            type: "date",
            required: true,
        },
        {
            name: "noticePeriodStatus",
            label: "Notice Period Status",
            type: "select",
            required: true,
            options: [
                { label: "Full notice period to be served", value: "full-notice" },
                { label: "Notice pay in lieu of notice", value: "pay-in-lieu" },
                { label: "Immediate termination (for cause)", value: "immediate" },
                { label: "Garden leave during notice", value: "garden-leave" },
            ],
        },
        {
            name: "noticePeriodDays",
            label: "Notice Period (Days)",
            type: "text",
            placeholder: "e.g. 30",
            required: false,
        },
        {
            name: "settlementDetails",
            label: "Final Settlement Details",
            type: "textarea",
            placeholder: "e.g. Pending salary, earned leave encashment, gratuity (if applicable), bonus pro-rata",
            required: false,
            description: "List all settlement components. Gratuity applicable after 5 years (Payment of Gratuity Act 1972).",
        },
        {
            name: "assetReturnList",
            label: "Company Assets to Return",
            type: "textarea",
            placeholder: "e.g. Laptop, ID card, access cards, parking pass, company phone",
            required: false,
        },
        {
            name: "includeNDAReminder",
            label: "Remind of Ongoing NDA Obligations?",
            type: "checkbox",
            required: false,
            description: "Reference existing NDA/confidentiality obligations that survive termination.",
        },
        {
            name: "includeNonDisparagement",
            label: "Include Non-Disparagement Clause?",
            type: "checkbox",
            required: false,
        },
        {
            name: "includeAppealRight",
            label: "Include Right to Appeal / Grievance?",
            type: "checkbox",
            required: false,
            description: "Allow the employee to appeal the decision within a stated timeframe.",
        },
    ],
    defaultClauses: [
        "Letter Header & Date",
        "Employee Details",
        "Termination Reason & Grounds",
        "Effective Date of Termination",
        "Notice Period Terms",
        "Final Settlement & Dues",
        "Company Property Return",
        "Access Revocation",
        "Confidentiality & NDA Reminder",
        "Non-Disparagement",
        "Right to Appeal / Grievance",
        "Signature Block — HR / Director",
    ],
};
