import type { DocumentTemplate } from "@/types";

export const vendorOnboardingTemplate: DocumentTemplate = {
    type: "vendor-onboarding",
    label: "Vendor Onboarding Letter",
    description:
        "Formalise a vendor engagement with scope, payment terms, SLAs, and compliance requirements.",
    isTwoParty: true,
    fields: [
        {
            name: "vendorType",
            label: "Type of Vendor",
            type: "select",
            required: true,
            options: [
                { label: "Software / IT Services", value: "it-services" },
                { label: "Marketing / Creative Agency", value: "marketing" },
                { label: "Legal / Compliance Firm", value: "legal" },
                { label: "Logistics / Operations", value: "logistics" },
                { label: "Consulting / Advisory", value: "consulting" },
                { label: "Hardware / Manufacturing", value: "hardware" },
                { label: "Freelancer / Individual Contractor", value: "freelancer" },
            ],
        },
        {
            name: "scopeOfWork",
            label: "Scope of Work",
            type: "textarea",
            placeholder: "Detailed description of services/deliverables expected from the vendor.",
            required: true,
        },
        {
            name: "contractValue",
            label: "Contract Value (₹)",
            type: "text",
            placeholder: "e.g. ₹5,00,000",
            required: true,
        },
        {
            name: "paymentTerms",
            label: "Payment Terms",
            type: "select",
            required: true,
            options: [
                { label: "Net 15 (15 days from invoice)", value: "net-15" },
                { label: "Net 30 (30 days from invoice)", value: "net-30" },
                { label: "Net 45 (45 days from invoice)", value: "net-45" },
                { label: "Milestone-based", value: "milestone" },
                { label: "50% Advance + 50% on Delivery", value: "50-50" },
            ],
        },
        {
            name: "contractDuration",
            label: "Engagement Duration",
            type: "select",
            required: true,
            options: [
                { label: "3 Months", value: "3-months" },
                { label: "6 Months", value: "6-months" },
                { label: "1 Year", value: "1-year" },
                { label: "Project-based (until completion)", value: "project" },
                { label: "Ongoing (auto-renew)", value: "ongoing" },
            ],
        },
        {
            name: "slaRequirements",
            label: "SLA / Performance Requirements",
            type: "textarea",
            placeholder: "e.g. 99.5% uptime, 24-hour response time, weekly progress reports...",
            required: false,
        },
        {
            name: "jurisdiction",
            label: "Jurisdiction",
            type: "select",
            required: true,
            options: [
                { label: "Mumbai", value: "Mumbai" },
                { label: "Delhi", value: "Delhi" },
                { label: "Bangalore", value: "Bangalore" },
                { label: "Chennai", value: "Chennai" },
                { label: "Hyderabad", value: "Hyderabad" },
                { label: "Pune", value: "Pune" },
            ],
        },
        {
            name: "includeNDA",
            label: "Include Confidentiality / NDA Clause?",
            type: "checkbox",
            required: false,
        },
        {
            name: "includeIPClause",
            label: "Include IP Assignment Clause?",
            type: "checkbox",
            required: false,
            description: "All deliverables and IP created become the company's property.",
        },
        {
            name: "includeInsurance",
            label: "Require Professional Indemnity Insurance?",
            type: "checkbox",
            required: false,
        },
        {
            name: "includeGSTCompliance",
            label: "Require GST Compliance Declarations?",
            type: "checkbox",
            required: false,
            description: "Vendor must provide valid GSTIN-based invoices for ITC claiming.",
        },
        {
            name: "complianceDocuments",
            label: "Required Compliance Documents",
            type: "textarea",
            placeholder: "e.g. GST Certificate, PAN, Bank Details, MSME Registration...",
            required: false,
        },
    ],
    defaultClauses: [
        "Onboarding Letter Header & Date",
        "Vendor Identification & Registration",
        "Scope of Work & Deliverables",
        "Contract Value & Payment Terms",
        "Engagement Duration & Renewal",
        "SLA & Performance Standards",
        "Confidentiality & NDA",
        "IP Assignment",
        "Compliance Requirements",
        "GST & Tax Compliance",
        "Termination & Notice Period",
        "Dispute Resolution",
        "Governing Law",
        "Acceptance & Signature Block",
    ],
};
